### ISSUE TITLE
Support Printing of Route Directions

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#1]
The directions tool should be able to generate a document with the current route, suitable for printing. 

This document should include:
- the waypoints 
- a list of the directions for the route through the waypoints
- a map showing the route

Ideally on one page.

**Comment by NicoledeGreef** [comment]
Also needs to include reports/alerts specific to segments on the route. Itinerary text should be blue for directions on a truck route, and red, for segments not on a truck route.

**Comment by gk-tl** [comment]
Agreed. The route itinerary should reflect the colour coding of the generated route:

- blue = Proposed Route
- red = Unverified Route

We previously discussed matching the font colour of the list of directions with the generated route colours (i.e., blue text for directions on a "Proposed Route" and red text for directions on an "Unverified Route."

![image](https://user-images.githubusercontent.com/59627982/72026778-98689b00-3231-11ea-8d1f-ecf49c8b19ec.png)

**Comment by gk-tl** [comment]
Note: Overlaps with ticket #13.

**Comment by gk-tl** [comment]
> Also needs to include reports/alerts specific to segments on the route. Itinerary text should be blue for directions on a truck route, and red, for segments not on a truck route.

Agreed.

**Comment by NicoledeGreef** [comment]
Thanks for the notes.  I will close this one and we will fulfill the finer point  via tickets #13 and #26.
