### ISSUE TITLE
integrate changes to directions service into SMK

### ISSUE THREAD

**Issue by qqnluaq** [bcgov/smk-tlink#10]
integrate changes to directions service into SMK

**Comment by NicoledeGreef** [comment]
relates to: https://github.com/bcgov/smk-tlink/issues/8

**Comment by NicoledeGreef** [comment]
@qqnluaq - does this ticket pertain to the extra data that the route planner is going to supply in the next few weeks?

**Comment by qqnluaq** [comment]
@NicoledeGreef yes, i'm still waiting for route planner to give me the notification info.

**Comment by NicoledeGreef** [comment]
The route planner API now fully implements the partitioning requirements identified by TransLink so the CVRP is now getting all the data needed to style the route. It will also get the list of munis the best route traverses which can be used with an additional table of vehicle dimensions to determine whether or not a vehicle is a truck in those munis. 

Note the values for the **&partition** parameter.

https://ssl.refractions.net/ols/router/directions.json?apikey=11dd756f680c47b5aef5093d95543738&criteria=fastest&disable=sc,tf,ev,td,&departure=2020-01-13T14:16:00-08:00&followTruckRoute=true&partition=isTruckRoute,isFerry,locality&truckRouteMultiplier=10&points=-123.2923164,48.4432256,-123.5342729,48.7458149

**Comment by NicoledeGreef** [comment]
The other notifications are to be found in a table called "applicationmsgs" which was housed in postGIS in the old Beta app.  Working on locating a copy of that for @qqnluaq as well as "trfinal".  updated version of these tables are coming Jan 24th.

**Comment by gk-tl** [comment]
Complete. Thank you.
