### ISSUE TITLE
[Data Update to fix] Missing advisory description/note & incorrect link for Pac Hwy Border Crossing

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#106]
@al-tabb and/or @NicoledeGreef 

![image](https://user-images.githubusercontent.com/59627982/77100363-bf321300-69d2-11ea-9c7a-7318d36d148b.png)

---
Follow the links for information about Canada - United States border crossing requirements for Highway Carriers (Trucks):

- For northbound trucks entering Canada – Canada Border Services Agency (CBSA): 
   https://www.cbsa-asfc.gc.ca/prog/aci-manif-ipec/menu-eng.html

- For southbound trucks entering the United States – US Customs and Border Protection (US CBP): 
   https://www.cbp.gov/border-security/ports-entry/carriers
---

**Comment by NicoledeGreef** [comment]
@al-tabb  - is this a data update?

**Comment by al-tabb** [comment]
Yes, should be sending along shortly

**Comment by al-tabb** [comment]
Corrected.  Updated data set provided by email.

**Comment by gk-tl** [comment]
Thank you...almost there...

Bylaw link is not applicable in this case (should be a null value).

Is it possible to link to the website addresses and include both the northbound/southbound links in the same notice? As written, the notice refers to the CA crossing (Douglas) and US crossing (Peace Arch) and instructs users to follow the links (plural) for more information.

The Douglas/Peace Arch border crossing does not serve commercial traffic. All commercial traffic should report to the Pacific Highway Truck Crossing on Hwy 15 / SR 543. Follow the links for information about Canada - United States border crossing requirements for Highway Carriers (Trucks):

- For northbound trucks entering Canada – Canada Border Services Agency (CBSA): https://www.cbsa-asfc.gc.ca/prog/aci-manif-ipec/menu-eng.html

- For southbound trucks entering the United States – US Customs and Border Protection (US CBP): https://www.cbp.gov/border-security/ports-entry/carriers

![image](https://user-images.githubusercontent.com/59627982/77988584-957dc380-72d1-11ea-8e6c-a3bf39e7a785.png)

**Comment by qqnluaq** [comment]
the last comment should be a new ticket

**Comment by al-tabb** [comment]
@gk-tl For the southbound segment I only put the applicable link for trucks entering USA and for the northbound segment I only put the link for trucks entering Canada.  Does this make sense or do you want to show both links regardless of the segment's direction?

**Comment by al-tabb** [comment]
@qqnluaq @gk-tl I think that perhaps in the future all links should be handled by TransLink in the data (i.e. include "<a href="xxx"></a?>" in the data.  Right now I believe we have a mix of both plain text links (which are turned into hyperlinks by Ben) and hyperlinks supplied by TransLink.  Thoughts?

**Comment by gk-tl** [comment]
The notice is written in reference to both southbound and northbound. It makes most sense to show both link regardless of direction.

Regarding where the links are handled, I have no strong preferences - whatever makes most sense to you and Nicole/Ben.

**Comment by al-tabb** [comment]
Darn, I thought I was being smart leaving out one of the notices based on direction.  That's an easy change though.

**Comment by qqnluaq** [comment]
Its easier for the app to be consistent with how it handles links if the data contains just URLs. The cleanest way I think is the example given by 'Designated Municipal Truck Route', whee there is a field for the URL ('BylawLink'), and a field for the human readable presentation of the link ('Bylaw'). This allows the app to generate a nice, clearly labelled link.

**Comment by al-tabb** [comment]
Completed. Updated data sent via email.

**Comment by NicoledeGreef** [comment]
In Delivery (https://translink-d.apps.gov.bc.ca/trp/) there are exposed HTML tags in the Advisory Description for the Truck Border Crossing and Peace Arch Border Crossing.  Didn't find any other instances of this clicking around the Advisory symbols on the map.

![image](https://user-images.githubusercontent.com/26335003/81456349-cfe74580-9146-11ea-9ef3-f6660f9bef1e.png)

**Comment by NicoledeGreef** [comment]
looks good to me.  @gk-tl , @al-tabb  - can you please review?

**Comment by gk-tl** [comment]
All looks good. Complete. Thank you.
