### ISSUE TITLE
[Data Update to fix] Typo in DG Restriction Description & Link Name

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#107]
@al-tabb and/or @NicoledeGreef 

![image](https://user-images.githubusercontent.com/59627982/77101733-028d8100-69d5-11ea-8534-1071a23d9af7.png)

Remove "then"
The link name should be "BC Tunnel Transportation of Dangerous Goods Regulation" rather than "Link"

**Comment by al-tabb** [comment]
I will make the change.  About to send of some minor updates to the Truck Routes dataset so I can send these at the same time.

**Comment by gk-tl** [comment]
Thanks Alan.

**Comment by al-tabb** [comment]
Completed, new data set sent via email.

**Comment by gk-tl** [comment]
Is it possible to rename the link from "Link" to "BC Tunnel Transportation of Dangerous Goods Regulation"

![image](https://user-images.githubusercontent.com/59627982/77989953-ed69f980-72d4-11ea-8f40-931e439e1d52.png)


Also, on a low priority, please remove highlighted "the":
![image](https://user-images.githubusercontent.com/59627982/77989918-d4614880-72d4-11ea-86b2-808695d16e17.png)

**Comment by gk-tl** [comment]
The link to the regs is not working:

http://www.bclaws.ca/EPLibraries/bclaws_new/document/ID/freeside/14_275_2006

**Comment by qqnluaq** [comment]
fixed in dev

**Comment by NicoledeGreef** [comment]
verified in https://translink-d.apps.gov.bc.ca/trp/?config=./config/test-services.json

![image](https://user-images.githubusercontent.com/26335003/78084482-2bb2f780-736d-11ea-87eb-defaaeffd972.png)

"**the** section 4.15" has to be modified in the data set, however.

**Comment by gk-tl** [comment]
Thank you.

@al-tabb please remove highlighted "the" in the data set.

![image](https://user-images.githubusercontent.com/59627982/78084846-22765a80-736e-11ea-8e58-10a958b39620.png)

**Comment by al-tabb** [comment]
Completed. Updated data sent via email.
