### ISSUE TITLE
Address for Inspection Stations is not displaying

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#108]
![image](https://user-images.githubusercontent.com/59627982/77102945-e25ec180-69d6-11ea-9335-a77e9a9ce1d7.png)

**Comment by qqnluaq** [comment]
also cardlock wasn't displaying correctly

**Comment by gk-tl** [comment]
Indeed. Thanks for catching that.

**Comment by gk-tl** [comment]
Complete. Thank you.
