### ISSUE TITLE
Accomodate Coquitlam vehicle definition bylaw change

### ISSUE THREAD

**Issue by mraross** [bcgov/smk-tlink#109]
From Al Tabbernore:

 "... Coquitam has recently changed their bylaw and their truck definition weight is now 11,800 kg (previously was 13,600 kg) ... "

So if we enter a truck weight of 10,000 kg and we produce a route through Coquitlam we should see this message pop up and Coquitlam showing up in the list.  If we enter a truck weight of 12,000 kg we should not see this message for Coquitlam.

**Comment by gk-tl** [comment]
Complete. Thank you.
