### ISSUE TITLE
In TRP app, route planner requests, criteria parameter is incorrectly set to shortest

### ISSUE THREAD

**Issue by mraross** [bcgov/smk-tlink#110]
criteria should be set to fastest; otherwise turn costs and speed limits will be ignored when determining best route. All of our benchmark testing has been done with criteria=fastest.

**Comment by NicoledeGreef** [comment]
@mraross - please review and let us know if we can close this issue.

https://bcgov.github.io/smk-tlink/?config=./config/test-services.json

**Comment by mraross** [comment]
Verified using:
https://bcgov.github.io/smk-tlink/?config=./config/test-services.json

Looking good!
