### ISSUE TITLE
Legend Entry - Overheard structure with/without height marker

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#111]
Please update/revise legend entries for height clearance layer, as follows:

Overhead structure with posted height
Overhead structure without posted height

![image](https://user-images.githubusercontent.com/59627982/77370517-50c8ba00-6d1e-11ea-9779-dcca2f8c7d8f.png)

This will help align with ticket 243: https://github.com/bcgov/ols-router/issues/243

**Comment by al-tabb** [comment]
@qqnluaq Please filter the GM_OverheadStructures data set as follow to create these layers:
Overhead structure with posted height -> Posted_Limit = 'Y'
Overhead structure without posted height -> Posted_Limit != 'Y'

This allows us to include edge cases where overhead structures have posted clearances on municipal websites but no actual sign.

**Comment by gk-tl** [comment]
Complete. Thank you.
