### ISSUE TITLE
Revised Disclaimer

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#112]
Further to ticket #42, revised disclaimer as reviewed by TL legal:

Launch-ready version (reference to "BETA" struck out):

---
This website (the Truck Route Planner (TRP)) and all of the information it contains are provided "as is" without warranty of any kind, whether express or implied. All implied warranties, including, without limitation, implied warranties of merchantability, fitness for a particular purpose, and non-infringement, are hereby expressly disclaimed.

Links and references to any other websites are provided for information only and listing shall not be taken as endorsement of any kind. TransLink or any of its partners or stakeholders (including, without limitation, the Province of BC) are not responsible for the content or reliability of the linked websites and do not endorse the content, products, services or views expressed within them.

Under no circumstances will TransLink or any of its partners or stakeholders (including, without limitation, the Province of BC) be liable to any person or business entity for any direct, indirect, special, incidental, consequential, or other damage based on any use of this website or any other website to which this site is linked, including, without limitation, any lost profits, business interruption, or loss of programs or information, even if TransLink or any of its partners or stakeholders (including, without limitation, the Province of BC) have been specifically advised.
 
TransLink and the Province of BC, in their sole discretion, may at any time without notice revise the content and features of this website and the terms and conditions of its use, or terminate this website at any time, for any reason, without any notice and without any liability to any person or business entity.

This website is intended to be used as a pre-trip planner. Do not operate a vehicle while using this website.

By proceeding, you are accepting this disclaimer, and you are indicating you understand the limitations of this website.
 
I accept the disclaimer and understand the limitations of this website

---

Mark-up from original:
![image](https://user-images.githubusercontent.com/59627982/77481937-fee96800-6de1-11ea-9ee8-63c743439d66.png)

@al-tabb please include this version of the disclaimer with all data sets.

**Comment by gk-tl** [comment]
@NicoledeGreef  As far as TL is concerned, this is complete (thank you for updating). Out of an abundance of caution, it may be prudent to double check this also holds for the Province.

**Comment by NicoledeGreef** [comment]
@AlexanderRitchie  - would you please take a look at the Disclaimer and let us know if it's good to go?
The most up to date content is visible here:
https://bcgov.github.io/smk-tlink/?config=./config/test-services.json

**Comment by AlexanderRitchie** [comment]
Looks good to me!
Thanks,
Alex
