### ISSUE TITLE
Missing fields in "Overhead structure with posted height" layer

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#114]
Height clearances, streetview link etc missing in "Overhead structure with posted height" layer

![image](https://user-images.githubusercontent.com/59627982/77651988-d0c36f80-6f2a-11ea-80f5-117f5ccb92d9.png)

**Comment by qqnluaq** [comment]
The field names for this layer have not been stable with each version of the db.

gdb/2020-01-30-TRPCartographicLayers.gdb.zip
[
  "Comments",
  "Height_Lane1centre_O",
  "Height_Lane1centre_P",
  "Height_Lane2_O",
  "Height_Lane2_P",
  "Height_Lane3_O",
  "Height_Lane3_P",
  "Height_Lane4_O",
  "Height_Lane4_P",
  "Height_Sign",
  "Information_Link",
  "MRN_Structure_ID",
  "OVERHEAD",
  "O_Cardinality",
  "P_Cardinality",
  "Posted_Limit",
  "Route",
  "Streetview_Link",
  "Structure_Name",
  "Structure_Owner",
  "Structure_Type",
  "TruckRoute"
]


gdb/2020-03-11-TRPCartographicLayers.gdb.zip
[
  "Comments",
  "Height_Lane1centre_O",
  "Height_Lane1centre_P",
  "Height_Lane2_O",
  "Height_Lane2_P",
  "Height_Lane3_O",
  "Height_Lane3_P",
  "Height_Lane4_O",
  "Height_Lane4_P",
  "Height_Sign",
  "Information_Link",
  "MRN_Structure_ID",
  "OVERHEAD",
  "O_Cardinality",
  "P_Cardinality",
  "Posted_Limit",
  "Route",
  "Streetview_Link",
  "Structure_Name",
  "Structure_Owner",
  "Structure_Type",
  "TruckRoute"
]


gdb/2020-03-24-TRPCarto1.gdb.zip
[
  "Comments",
  "HeightL1CO",
  "HeightL1CP",
  "HeightL2O",
  "HeightL2P",
  "HeightL3O",
  "HeightL3P",
  "HeightL4O",
  "HeightL4P",
  "HeightSign",
  "Information_Link",
  "Ocardinal",
  "Overhead",
  "Pcardinal",
  "Posted_Limit",
  "Route",
  "StructName",
  "StructType",
  "Structure_Owner",
  "StviewLink",
  "TruckRoute"
]

The most recent update changed most of the field names. The code in the app was expecting the previous version of the names. Which are correct?

These field names are part of the code. If they change, things will break.

**Comment by gk-tl** [comment]
Thanks Ben. Looping @al-tabb into this ticket. Which version of the field names is the app currently using, and am I correct in assuming that reverting the field names in the most recent version of the database will address the isssue? (is it gdb/2020-03-11-TRPCartographicLayers.gdb.zip?)

**Comment by qqnluaq** [comment]
Yes, thats correct. the code expects the names from the 2020-03-11 version

**Comment by gk-tl** [comment]
Thanks Ben.

**Comment by al-tabb** [comment]
@qqnluaq Apologies for the mix up.  Here is the dataset with the previous field names.
[GM_OverheadStructures.gdb.zip](https://github.com/bcgov/smk-tlink/files/4396449/GM_OverheadStructures.gdb.zip)

**Comment by gk-tl** [comment]
Thanks for looking after this Alan.

**Comment by gk-tl** [comment]
Complete. Thank you.
