### ISSUE TITLE
Cartographic Layer Missing - Yellow Lines

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#118]
Cartographic layer missing - Municipal Road with no truck travel restrictions (yellow lines)

![image](https://user-images.githubusercontent.com/59627982/77698749-63393280-6f6e-11ea-896f-ee9385caf24a.png)

**Comment by NicoledeGreef** [comment]
i think this one has been rectified in the interim period (it was filed 5 days ago).

**Comment by gk-tl** [comment]
Complete. Thank you.
