### ISSUE TITLE
Municipal roads with no truck travel restrictions - Maple Ridge

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#119]
@al-tabb  @mraross Please add the following roads to the layer "municipal roads with no truck travel restrictions" (yellow) and the ITN:

![2020-03-26 TRP Maple Ridge Route Additions](https://user-images.githubusercontent.com/59627982/77704323-0a6f9700-6f7a-11ea-987e-ab8d254c7b08.jpg)

Note: Verified with staff @ Maple Ridge on March 26, 2020.

**Comment by gk-tl** [comment]
Related to ticket 245:  https://github.com/bcgov/ols-router/issues/245

**Comment by gk-tl** [comment]
@al-tabb and @mraross In addition to the streets listed above, please add 207 Street between Lougheed Hwy and Dewdney Trunk Road.

Note: Verified with staff at @Maple Ridge on March 26.

**Comment by mraross** [comment]
Super, thanks for the quick research on this Greg. I will update the route planner ticket appropriately.

**Comment by gk-tl** [comment]
Based on conversation with @mraross on March 30, 2020, the additional roads will be added for ITN release end of April 2020 (which is OK).

@NicoledeGreef will it be possible to add these to the cartographic layer before then? 

@al-tabb please update cartographic/routing data sets and forward to Nicole/Graeme.

**Comment by NicoledeGreef** [comment]
Sure - let's close this ticket and start a new one for incoming data.
