### ISSUE TITLE
image paths break in OpenShift

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#122]
The waypoint icons and spinner are not rendering in OpenShift deployed apps.  The path has an extra slash between lib and images which it seems is not acceptable to OpenShift but OK on GH pages.

e.g.
https://translink.apps.gov.bc.ca/trp/lib//images/tool/directions/marker-icon-green.png 
https://translink.apps.gov.bc.ca/trp/lib//images/tool/directions/marker-icon-red.png 
https://translink.apps.gov.bc.ca/trp/lib//images/tool/directions/marker-icon-blue.png

**Comment by dkelsey** [comment]
I had an error for:
a **404**

https://translink.apps.gov.bc.ca/trp/layers/overhead-directional-signs/images/directions.svg

and 

https://translink.apps.gov.bc.ca/trp/lib//images/spinner.gif

**Comment by mraross** [comment]
?Directions sign works for me. spinner works when I drop the duplicate slash ("/") as Nicole pointed out.

________________________________

**Comment by qqnluaq** [comment]
fixed doubled slashes in some image urls, which seems to cause webserver in openshift deploy to fail

**Comment by NicoledeGreef** [comment]
verified as fixed in https://translink-d.apps.gov.bc.ca/trp/?config=./config/test-services.json

**Comment by NicoledeGreef** [comment]
Spinner fix verified in: https://translink-d.apps.gov.bc.ca/trp/?config=./config/test-services.json
