### ISSUE TITLE
Port Access Notices/Reports

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#123]
@al-tabb @NicoledeGreef @gleeming @mraross 

Please update advisory descriptions and notices/reports for port access. For example, Deltaport notice currently states:

"Roberts Bank Rd, Delta: Restricted Access - Port of Vancouver"

Should state:

"Roberts Bank Rd, Delta: This route includes a Port Restricted Access road. All container trucks accessing port container terminals must hold a valid Truck License System (TLS) licence. The TLS program requires all drayage companies and trucks draying marine containers to or from the port to enter into an Access Agreement from the port authority prior to accessing port facilities. This applies to all parties draying, both local and long haul. Follow the link for more information about the TLS and port access requirements: https://www.portvancouver.com/truck-rail/truck" 

Please see related ticket: https://github.com/bcgov/ols-router/issues/258

**Comment by al-tabb** [comment]
Completed. Updated data sent via email.

**Comment by qqnluaq** [comment]
This update is to the route planner

**Comment by NicoledeGreef** [comment]
@mraross  -looks like this update is applicable to the route planner.  can you please confirm?

**Comment by mraross** [comment]
Yes it is.

**Comment by gleeming** [comment]
I have updated the truck notice description for 6 Roberts Bank Rd segments.  The change will be built into the May RoutableBC inputs.

**Comment by NicoledeGreef** [comment]
Thanks!
