### ISSUE TITLE
geocoding request missing brief, minScore and echo parameters

### ISSUE THREAD

**Issue by mraross** [bcgov/smk-tlink#125]
1. Without brief=true, geocoder responses are bigger. This may be noticeable by users during autocompletion in limited-bandwidth situations.
 
2. Without minScore=50, poor address matches will be shown to the user which may cause confusion.

3. Without echo=true, any unmatched unit numbers will not be shown to the user. which may cause confusion. For example, if you type in:

  304-1175 Douglas St, Victoria, BC

without echo=true and if unit numbers for a given civic number are not known to the geocoder, the user will be shown the following:

        1175 Douglas St, Victoria, BC

Here is an example request that includes minScore and echo:

https://geocoder.api.gov.bc.ca/addresses.geojson?maxResults=5&outputSRS=4326&addressString=304-1175%20douglas%20st-&autoComplete=true&brief=true&locationDescriptor=accessPoint

**Comment by qqnluaq** [comment]
added `echo` & `minscore` parameters. I left `brief` as `true`, because the code depends on the detailed result object.

**Comment by NicoledeGreef** [comment]
@mraross  - can you please review the progress on this item?
Change is available at: 
https://github.com/bcgov/smk-tlink/issues/125

**Comment by mraross** [comment]
Looks good. I now see minScore=50 and echo=true included in GET request. Here's an example from the network console running https://translink-d.apps.gov.bc.ca/trp/

https://geocoder.api.gov.bc.ca/addresses.geojson?maxResults=5&outputSRS=4326&addressString=richardson--&autoComplete=true&locationDescriptor=accessPoint&locationMode=input&brief=false&minScore=50&echo=true

What is the locationMode parameter for? There is no such parameter in the geocoder API.

**Comment by qqnluaq** [comment]
`locationMode` is an SMK parameter that leaked into that request. Ill remove it

**Comment by mraross** [comment]
Great, thanks Ben.

**Comment by NicoledeGreef** [comment]
@mraross  - can you please review once more to ensure all is well and locationMode param is removed?

**Comment by mraross** [comment]
Verified. echo=true, minScore=50, and locationMode is removed. 

To confirm, I visited here:
https://translink-d.apps.gov.bc.ca/trp/

Turned on the developer tools.network console, entered an address, the trp generated a geocoder request that showed up in the network console as:

https://geocoder.api.gov.bc.ca/addresses.geojson?maxResults=5&outputSRS=4326&addressString=1175&autoComplete=true&locationDescriptor=accessPoint&brief=false&minScore=50&echo=true

**Comment by mraross** [comment]
Debugging tip: geocoder supports html output format which gives you a very readable report. The request above in html is:

https://geocoder.api.gov.bc.ca/addresses.html?maxResults=5&outputSRS=4326&addressString=1175&autoComplete=true&locationDescriptor=accessPoint&brief=false&minScore=50&echo=true

**Comment by NicoledeGreef** [comment]
thanks @mraross !
