### ISSUE TITLE
Site name dropped when adding a non-civic address to route waypoints

### ISSUE THREAD

**Issue by mraross** [bcgov/smk-tlink#126]
1. Enter Vanterm--. VanTerm -- Stewart St, Vancouver, BC pops up as follows:

![image](https://user-images.githubusercontent.com/11318574/78083863-92371600-736b-11ea-9daa-1b9dfbaf5fc4.png)

2. Select the VanTerm address from the list. The app displays the following route start point:

![image](https://user-images.githubusercontent.com/11318574/78083637-e7bef300-736a-11ea-9447-5f83eb3181ef.png)

The sitename, **VanTerm --**, has been dropped from the address.

**Comment by NicoledeGreef** [comment]
We never implemented; related to #82 which is in the Icebox for now.

**Comment by mraross** [comment]
I checked the geocoder response and the fullAddress did include the site name. Expected it to just work with no code-change required on Ben's part. No biggie.

**Comment by mraross** [comment]
This is actually a bug in the application.

The route below goes from:

     Richardson International -- Low Level Rd, District of North Vancouver, BC
to:
      Low Level Rd, North Vancouver, BC

but the "Richardson International --" was dropped from the start point address. 

![image](https://user-images.githubusercontent.com/11318574/78412850-c60f7700-75c9-11ea-8c78-88ce8db84f6f.png)

**Comment by NicoledeGreef** [comment]
@mraross  says "Vanterm--" should resolve to "Vanterm--" not "Stewart St".  There is no reason to drop "Vanterm--" from the waypoint description.  It does appear to be dropping the pin in the right place, however.

**Comment by NicoledeGreef** [comment]
@mraross - are you able to review this amendment? thanks.
https://translink-d.apps.gov.bc.ca/trp/

**Comment by mraross** [comment]
Done and verified. Thank you so much!
