### ISSUE TITLE
Printable directions enhancement

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#13]
The printable directions needs to include reports/alerts specific to segments on the route. Itinerary text should be blue for directions on a truck route, and red, for segments not on a truck route.

**Comment by NicoledeGreef** [comment]
At this point in time we expect the app to consume the notifications returned by the route planner web service.  These will be supplied monthly by TL and integrated into the Route Planner data store.  Fulfillment of this requirement is blocked until the route planner supplies results that include these notifications (can be fake data but some text needs to be supplied in order for the app to harvest and use it).

We also expect that we need to host a notifications lookup table based on truck definitions on a per municipality basis (i.e. municipal by-law driven rules).  Richmond may have a different definition of what constitutes a truck versus Delta versus Surrey and these need to be reflected in the app data store as well as associated notices,  the Route Planner will identify each segment of a route as being part of a specific muni can this can be used in the lookup query.

**Comment by qqnluaq** [comment]
colours fixed, and deployed

**Comment by cpspicer** [comment]
Given that the number of lines of text for alerts is unknown, and route dependent - it may be wise to have the last 'sheet' of the printable directions be dedicated to alerts and notifications.  Just a thought - might be a better way to link the alert to the segment, but the UI might be challenging otherwise.

**Comment by cpspicer** [comment]
And possibly use page 1 for the 'overview map' showing entire route.

**Comment by qqnluaq** [comment]
colours fixed on printout, deployed.

**Comment by qqnluaq** [comment]
added overview on page 1, depoyed. I think it could be possible to have the notifications & alerts on page 1 as well, just push up the bottom edge of the map.

**Comment by NicoledeGreef** [comment]
i like the addition of the overview map.  am wondering if these text snippets should be red though?

![image](https://user-images.githubusercontent.com/26335003/72283561-de3baf80-35f3-11ea-8d14-9994aaa52b04.png)

![image](https://user-images.githubusercontent.com/26335003/72283523-cebc6680-35f3-11ea-93fa-c974fe8a55ec.png)


@al-tabb and @gk-tl - con you confirm whether this is the expectation?

In discussing this with colleagues we came to the conclusion that the colour differentiation works well on screen but may not be as useful if users print in grayscale (not everyone has access to a colour printer).  red does not come across as optimally in grayscale printing.  interested to know what translink thinks and if any feedback is received on the subject.

**Comment by gk-tl** [comment]
Thank you for flagging this. 

The objective is to provide a clear distinction between the directions for proposed route segments and unverified route segments for the print itinerary. We are open to suggestions about how to best achieve this while keeping the level of effort reasonable. 

**Possible solution:** In addition to colour differentiation for directions (blue vs red), consider one of these approaches (or if possible, a combination of them).

- Use "blue + bold + larger font size" for text that applies to a proposed route and red + italic text + smaller font for text that applies to unverified routes. Include a legend on the last page of the printed itinerary.

- Add symbols (e.g., asterisk) with the text that applies to unverified routes.
 
Include a legend on the last page (or on each page). See attached example.

Cheers,

Greg
[Printable Directions - Colour.docx](https://github.com/bcgov/smk-tlink/files/4056477/Printable.Directions.-.Colour.docx)
[Printable Directions - Grayscale.pdf](https://github.com/bcgov/smk-tlink/files/4056478/Printable.Directions.-.Grayscale.pdf)

**Comment by NicoledeGreef** [comment]
Thanks for the examples; that is helpful.  I like the idea of font differentiation as well.

**Comment by gk-tl** [comment]
> Given that the number of lines of text for alerts is unknown, and route dependent - it may be wise to have the last 'sheet' of the printable directions be dedicated to alerts and notifications. Just a thought - might be a better way to link the alert to the segment, but the UI might be challenging otherwise.

Indeed. Thank you for flagging this.

Depending on the route and vehicle dimensions and weights, the reports can be fairly extensive. 

I hesitate to suggest how to include reports as I'm not sure what the associated UI challenges are. I'm also not clear whether reports will be provided as part of the "route detail" [directions] feature or as a stand-alone feature. 

In the TL BETA, reports are a stand-alone feature, but the TL BETA doesn't provide turn-by-turn directions. Combining the two (i.e., directions and reports) makes sense, but again, I'm not sure whether this presents challenges.

Happy to receive a recommendation about incorporating reports in the full production TRP, and by extension, how to display reports on the route detail printout. 

![Reports](https://user-images.githubusercontent.com/59627982/72306876-68ecd080-362d-11ea-84da-0656f3eda1b4.png)

**Comment by qqnluaq** [comment]
There is a problem with styling the directions according to the flags for the segment that direction is in, the beginning & end of segments doesn't necessarily fall on the points used for directions. For example:

![image](https://user-images.githubusercontent.com/20274603/72838034-651c0800-3c44-11ea-8d08-0584bac1f9da.png)

The circled area is the boundary between 2 segments (not designated truck route, and truck route), but it is not a point that has a direction associated with it.

So it is a bit unclear how to style the direction #2, should it be a proposed route, or an unverified route? It could be argued to be both.

One possible solution is for me to insert extra direction nodes for this case.

Another possible solution is for the route planner to always start & stop segments at points that have directions associated with them.

**Comment by cmhodgson** [comment]
There is no forced correspondence between truck routes and turns; truck routes will sometimes end or start in places where there would be no direction required. This would require inserting additional directions such as "continue north on blanshard street (which is now a truck route)." Currently the partition function is separate from the directions function; it would be possible to do this but I'm somewhat against the idea and it would be possible to do on the client side (but probably easier on the server side). I'm not sure it really makes sense to style the directions based on the truck route status of that portion of the route, given the lack of correspondence between the two.

If we want the reports to be a part of the directions instead of being global, that can certainly be done as the report (aka. notification) object is being connected directly to individual segments. It could work the way ferry schedules/waits do, where there is a notification object attached to the direction when the ferry is entered. This would force an additional direction to be added, it might be "continue on ..." and then the direction would also have the notification attached.

**Comment by gk-tl** [comment]
Thank you for flagging this Could we schedule a call to walk through this? It think the approach is to weigh the solutions identified above against level of effort. 

@al-tabb

**Comment by NicoledeGreef** [comment]
Talking with @mraross, he, @al-tabb, and @cmhodgson discussed on Jan 22.  If a leg of the route starts out as truck use blue as the font color and if it starts out a non-truck route use red for the font color.

The directions don't necessarily break within a leg when there is no change in direction.  

Rare case:  single leg rarely contains both a truck route and non-truck route portion.

**Comment by NicoledeGreef** [comment]
@mraross, @cmhodgson , @al-tabb, @gk-tl , @qqnluaq , and @NicoledeGreef held a meeting on Jan 23rd to discuss.  During that discussion @qqnluaq conveyed the idea of the mapping app inserting advisory text when these transitions are detected.  Level of effort is relatively low (est. to be 4 hours).

**Comment by NicoledeGreef** [comment]
Discussed during call with @gk-tl and @al-tabb on Jan 24th.  

- Confirmed segment based notifications should be included as appropriate.
- General notifications should be included starting on Page 2.
- The very last page of the printable directions should include the Application Disclaimer text.

**Comment by qqnluaq** [comment]
I'm unclear if we are still doing the different coloured text depending on the type of route segment. I've implemented inserting advisory text in between directions when the segment type changes. A preview until I deploy it:
[BETA - CVRP - Translink.pdf](https://github.com/bcgov/smk-tlink/files/4131011/BETA.-.CVRP.-.Translink.pdf)

**Comment by gk-tl** [comment]
Looks good, noting the following:

- "Starting Proposed Route" should be "Starting Potential Route" 

- I think it would be helpful to use a combination of colour and font differentiation. For example:

> Use "blue + bold + larger font size" for text that applies to a potential route and "red + italic text + smaller font" for text that applies to unverified routes.

Differentiating by font size may not be necessary / practical (i.e., blue + bold and red + italic may be sufficient for clearly communicating the distinction between the two types of generated routes when viewing on screen, printing in colour, or printing in gray scale).

**Comment by gk-tl** [comment]
Printable directions look great. Thank you for including the reports/notices and the definition of the generated route types + disclaimer on the last page.

**A few (hopefully minor) suggested tweaks:**

1) Providing notices/reports at the bottom of each page is OK if there is a technical limitation that requires doing it like this. If not, it would be better to place the notices/reports at the end of the printout (ahead of the generated route definitions). My concern is that the notices/reports for a given route can get fairly lengthy and may break across pages. 

2) Please add headings to the last page "Notices & Reports" (see #1 above) and "Disclosure and Limitation of Liability". See attached mark-up.

[BETA - TRP - Translink Route Printout (GK Markup).pdf](https://github.com/bcgov/smk-tlink/files/4135948/BETA.-.TRP.-.Translink.Route.Printout.GK.Markup.pdf)

**Comment by gk-tl** [comment]
The following is complete. Thank you.

`"Starting Proposed Route" should be "Starting Potential Route"

I think it would be helpful to use a combination of colour and font differentiation. For example:

Use "blue + bold + larger font size" for text that applies to a potential route and "red + italic text + smaller font" for text that applies to unverified routes.

Differentiating by font size may not be necessary / practical (i.e., blue + bold and red + italic may be sufficient for clearly communicating the distinction between the two types of generated routes when viewing on screen, printing in colour, or printing in gray scale).`

**Comment by gk-tl** [comment]
The following remains to be addressed:

> Providing notices/reports at the bottom of each page is OK if there is a technical limitation that requires doing it like this. If not, it would be better to place the notices/reports at the end of the printout (ahead of the generated route definitions). My concern is that the notices/reports for a given route can get fairly lengthy and may break across pages.

Please add headings to the last page "Notices & Reports" (see #1 above) and "Disclosure and Limitation of Liability". See attached mark-up.

**Comment by gk-tl** [comment]
Substantially complete. I will open a new ticket for item 2 above so we can close this one, which is quite long.

**Comment by NicoledeGreef** [comment]
New ticket is #63
