### ISSUE TITLE
Print preview cover page does not match route

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#132]
When generating the print preview I noticed that the route shown on the first page of the report didn't match the route I had generated.  It actually showed the previous route I had generated.  The rest of the report seems to match the current route correctly.

I'm able to reproduce this by:
1. Generating a route
2. Generating the report
3. Dragging the endpoint to a new location
4. Generating the report again

[TRP - Translink.pdf](https://github.com/bcgov/smk-tlink/files/4417663/TRP.-.Translink.pdf)

**Comment by gk-tl** [comment]
@al-tabb please confirm this issue is resolved. Appears complete to me.

**Comment by al-tabb** [comment]
Complete. Thanks.

**Comment by gk-tl** [comment]
Thanks everyone.
