### ISSUE TITLE
Temp Road Closure Layer

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#136]
@NicoledeGreef / @qqnluaq / @al-tabb Please incorporate the road closure for North Van (cartographic layer only). The data is available at the links below.
![image](https://user-images.githubusercontent.com/59627982/78401864-796a7280-75ae-11ea-8caf-95027be0a7c6.png)

http://regionalroads.com:8080/geoserver/cite/wms?service=WMS&version=1.1.0&request=GetMap&layers=cite%3AGM_TemporaryRoadClosuresExtent&bbox=-123.10095354775521%2C49.200291453099446%2C-122.91172357662022%2C49.32350653959952&width=768&height=500&srs=EPSG%3A4326&format=application/openlayers

http://regionalroads.com:8080/geoserver/cite/wms?service=WMS&version=1.1.0&request=GetMap&layers=cite%3AGM_TemporaryRoadClosures&bbox=-123.09415076495394%2C49.20046807684604%2C-122.91243796552611%2C49.32102851312752&width=768&height=509&srs=EPSG%3A4326&format=application/openlayers

**Comment by al-tabb** [comment]
@qqnluaq You won't be able to access the links above use these:
http://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosures&format=geojson&download=true
http://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosuresExtent&format=geojson&download=true

Alternatively I can send a FGDB with those files. Let me know if there's any issues with the field names and I can address that as well.

**Comment by gk-tl** [comment]
@al-tabb field names are provided here: https://github.com/bcgov/smk-tlink/issues/128

"GM_TemporaryRoadClosures"
[
 "ClosureDescription",
 "ClosureName",
 "EndDate",
 "Link",
 "Notes",
 "StartDate",
 "Status"
]
"GM_TemporaryRoadClosuresExtent"
[
 "ClosureDescription",
 "ClosureName",
 "EndDate",
 "Link",
 "Notes",
 "Shape_Area",
 "Shape_Length",
 "StartDate",
 "Status"
]

**Comment by al-tabb** [comment]
@gk-tl Thanks.
@qqnluaq Here's the FGDB with the correct field names.

[GM_TemporaryRoadClosures.gdb.zip](https://github.com/bcgov/smk-tlink/files/4429902/GM_TemporaryRoadClosures.gdb.zip)

**Comment by al-tabb** [comment]
@qqnluaq Not sure if this was mentioned previously..  These layers needs to be filtered as such:
Status = 'Active'

**Comment by NicoledeGreef** [comment]
@al-tabb @gk-tl  - can you please review this ticket?

**Comment by gk-tl** [comment]
Complete. Thank you.
