### ISSUE TITLE
Symbology in Edge not displaying properly

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#137]
Related to ticket #77 

Symbology in edge is not displaying properly (e.g., industrial areas)

![image](https://user-images.githubusercontent.com/59627982/78402840-25f92400-75b0-11ea-93b1-368839c56a98.png)

**Comment by NicoledeGreef** [comment]
Industrial Camps, Downtown Vancouver, and Temporary Road Closure Extent are the layer symbols not showing up in the Legend despite showing up on the map itself.  

![image](https://user-images.githubusercontent.com/26335003/81457148-fc509100-9149-11ea-8122-da085fd40446.png)

**Comment by NicoledeGreef** [comment]
verified in Edge
