### ISSUE TITLE
Report shows blank page and unexpected symbology

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#139]
This report has a blank page and instead of a dotted red line it shows a yellow/red dotted line.
In order to produce this I:
1. Generated a route
2. Generated the report
3. Dragged the endpoint of the route (inadvertently added a waypoint)
4. Generated the report again

[TRP - Translink.pdf](https://github.com/bcgov/smk-tlink/files/4429859/TRP.-.Translink.pdf)

**Comment by qqnluaq** [comment]
I have seen this issue in the past, but not lately. It is difficult to reproduce, and i can't do it now.

**Comment by gk-tl** [comment]
@al-tabb Further to Ben's comment, can you please try to replicate the issue, otherwise let's mark it as complete to clear the board. Thank you.

**Comment by al-tabb** [comment]
I wasn't able to reproduce the blank page.  Are the yellow lines in the report intentional?  Using yellow may be confusing as we have a couple of layers (Municipal/Federal Road with No Truck Travel Restrictions) that use the same yellow colour.  The user may misinterpret this information in the report.
![image](https://user-images.githubusercontent.com/59742145/82692818-3a06ec80-9c15-11ea-8c38-0eb547bc4b03.png)

**Comment by qqnluaq** [comment]
The yellow lines represent the entire route and shows the part of the route that isn't annotated on a particular page. Its there to provide continuity between pages.

**Comment by al-tabb** [comment]
What would the level of effort be to change the colour?

**Comment by qqnluaq** [comment]
minimal

**Comment by al-tabb** [comment]
OK, perhaps we should change it then.  I think a cyan/aquamarine colour would be distinct from our other layers. Perhaps something like this: #0bd9c8

**Comment by qqnluaq** [comment]
done.

**Comment by al-tabb** [comment]
Awesome, thanks Ben.

**Comment by al-tabb** [comment]
This ticket is completed.  Thank you.
