### ISSUE TITLE
"COVID-19 Relief” data integration

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#141]
Translink has been collecting data from various sources in order to create a layer termed "COVID-19 Relief".

**Comment by NicoledeGreef** [comment]
The earliest version of this dataset will establish the schema and some records so that it can be integrated into the application.  Updates to the data in the layer can be provided with ease once that is set up.

**Comment by al-tabb** [comment]
@NicoledeGreef The dataset will be ready this afternoon.  Is it OK to use the API to grab the geojson or do you prefer the file geodatabase?
http://trp.regionalroads.com/api/?data=GM_Covid19Relief&format=geojson&download=true

**Comment by NicoledeGreef** [comment]
we can give the geoserver extract a go. thanks!

**Comment by al-tabb** [comment]
Sounds good.  Just to confirm are you able to 'filter' on your end.  We are going to have a field 'Active' which specifies if we want to display the feature or not.  Is this possible?

**Comment by qqnluaq** [comment]
yes it is

**Comment by al-tabb** [comment]
Great, the dataset is now finalized and available at:
http://trp.regionalroads.com/api/?data=GM_Covid19Relief&format=geojson&download=true

For now we'd like to only show values were Active = true

I expect there will be a couple of small data changes (additional points) early next week but this schema will remain unchanged.

**Comment by al-tabb** [comment]
Here are the symbols we'd like to use.  These are based on the 'AmenityType' field as follows:
Cardlock -> TRP COVID19 Relief - Cardlock.png
Food Truck -> TRP COVID19 ReliefRestaurant.png
Hotel -> TRP COVID19 ReliefHotel.png
Inspection Station -> TRP COVID19 Relief - Inspection Station.png
Public Washroom -> TRP COVID19 Relief - Washrooms.png
Restaurant -> TRP COVID19 ReliefRestaurant.png
Temporary Respite Area -> TRP COVID19 Relief - Parking.png
Tourist Centre -> TRP COVID19 Relief - Inspection Station.png
[covid19reliefsymbols.zip](https://github.com/bcgov/smk-tlink/files/4532039/covid19reliefsymbols.zip)

**Comment by al-tabb** [comment]
We still need to confirm some things on our end before we can commit to pushing this to test/production.  I will keep you posted on our progress.

**Comment by al-tabb** [comment]
@qqnluaq Are you able to display aliases based on the values?  When these fields are equal to 1 (ParkingLot, CurbsideParking, FoodNearby, WashroomNearby, ShowersNearby, GarbageBinNearby) we'd like to have it display as 'Yes'.

Is this possible / easy for you to do?  Alternatively, I can change these fields to text and populate them with Yes/No going forward.

**Comment by qqnluaq** [comment]
@al-tabb yet its possible to reformat the values

**Comment by al-tabb** [comment]
@qqnluaq The hyperlinks currently do not work.  The current convention that seems to have developed with hyperlinks is:
-When there is a link within a larger block of text / multiple links I include the anchor tags
-When there is a field which only contains a hyperlink the anchor tags are handled on the front end

Does this convention work / make sense to you?

The following fields are hyperlink only:
StreetviewLink, DocumentLink, InformationLink
The following fields may have hyperlinks contained within larger blocks of text:
Terms of Use, Comments, ContactInfo, DirectionsToShowers, DirectionsToGarbageBin, DirectionsToFood, DirectionsToOtherAmenity

**Comment by qqnluaq** [comment]
updated build with these changes.
It should be noted that there are 3 attributes in the features that have a newline (`\n`) in their name. This is probably an overwight, Anyway I have to manually remove these from the attribute names, as it will cause problems. The attributes are:
`CurbsideParking`, `OtherAmenity` and `DirectionsToOtherAmenity`.

**Comment by al-tabb** [comment]
@qqnluaq Thanks for implementing those Ben.  Yes the newline character was not intentional and will be removed from the dataset going forward.

**Comment by al-tabb** [comment]
This spreadsheet specified the order of field names and the display names for each field name as we'd like them to display in the popup.
[COVID19ReliefSchemaUI.xlsx](https://github.com/bcgov/smk-tlink/files/4560602/COVID19ReliefSchemaUI.xlsx)

**Comment by qqnluaq** [comment]
Field Name (Dataset) | Display Name (UI)
-- | --
Name | Name
AmenityType | Amenity Type
Address | Address
BuildingType | Building Type
AmenityLocation | Amenity Location
StreetviewLink | Streetview Link
InformationLink | Information Link
DocumentLink | Document Link
OpenHours | Open Hours
ParkingLot | Parking Lot
ParkingLotHours | Parking Lot Hours
ParkingSpaces | Number of Parking Spaces
CurbsideParking | Curbside Truck Parking
CurbsideParkingHours | Curbside Truck Parking Hours
FoodNearby | Food Nearby
DirectionsToFood | Directions to Food Options
WashroomNearby | Washrooms Nearby
DirectionsToWashroom | Directions To Washrooms
ShowersNearby | Showers Nearby
DirectionsToShowers | Directions To Showers
GarbageBinNearby | Garbage Bin Nearby
DirectionsToGarbageBin | Directions To Garbage Bin
OtherAmenity | Other Amenities
DirectionsToOtherAmenity | Directions To Other Amenities
TermsOfUse | Terms Of Use
Comments | Comments and Additional Notes
ContactInfo | Contact Information
Active | [Not displayed]

**Comment by qqnluaq** [comment]
Another odd thing in this data that I have to fix manually: All these point features have a geometry type of 'Multipoint' when they in fact contain a single point. This was breaking the zoom to feature behaviour, so I fixed the data.

**Comment by al-tabb** [comment]
Does this mean multipoint geometry cannot be used at all going forward?  I used this geometry type intentionally in case there were multiple washroom locations at one place (at a park for example).  If not, this is not too big of a deal, just need to know for future updates.

**Comment by qqnluaq** [comment]
if there is an actual need for multipoint geometries, i can fix code to handle it. the type can be changed when it is needed

**Comment by al-tabb** [comment]
@qqnluaq The COVID-19 Relief dataset has been updated and is available here:
http://www.trp.regionalroads.com/api/?data=GM_Covid19Relief&format=geojson&download=true

Just a reminder that the field ParkingSpaces has changed from number to text.  Also just want to confirm that we will leave this dataset in dev/test only until Greg has a chance to review.

@NicoledeGreef I've created the metadata in draft form for this dataset.

**Comment by al-tabb** [comment]
@qqnluaq There is also a new 'AmenityType' called 'Rest Area'.  Here is the icon for that.
![restarea](https://user-images.githubusercontent.com/59742145/81876537-cb9c9d00-9537-11ea-9356-46bcf8dd78ca.png)

**Comment by qqnluaq** [comment]
These are the AmenityType's in the latest dataset. There were more changes than adding "Rest Area". 2 types were replaced with new names, 1 type was removed.

- "Cardlock"
- "Food Truck"
- "Hotel"
- "Inspection Station"
- "Tourist Centre"
- "Portable Toilet" (was "Public Washroom")
- "Rest Area" (new)
- "Temporary Truck Parking" (was "Temporary Respite Area")
- "Restaurant" (removed)

**Comment by NicoledeGreef** [comment]
hi ben - can you please add the metadata link as follows?

https://catalogue.data.gov.bc.ca/dataset/0e8f256a-8b2d-48d0-aea3-4398e61dc829

**Comment by gk-tl** [comment]
@NicoledeGreef @qqnluaq @al-tabb Thank you for integrating the COVID-19 relief data. It looks great! The layer is ready to be pushed to test/prod (no more changes), but please hold off displaying the data in prod until we have confirmed a formal announcement format and date with our respective comms teams. I hope to have a better sense of timing tomorrow (Friday, May 22).

**Comment by NicoledeGreef** [comment]
@gk-tl  - thanks for the review.  we will move to Test once all tickets have been verified and wait for the signal to go to Production.
