### ISSUE TITLE
ie 11 user notification

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#142]
If a user is running IE 11 or lower notify them that the TRP is an application that requires a modern web browser such as Chrome, Firefox, Edge or Safari. Currently a blank page is encountered. when ie11 is used.

**Comment by NicoledeGreef** [comment]
Is it feasible to remove the form elements as shown below?
![image](https://user-images.githubusercontent.com/26335003/80828254-d6e7e400-8b99-11ea-9331-d172d25c3e65.png)

**Comment by NicoledeGreef** [comment]
@qqnluaq  - is it feasible to hide the highlighted output when the site s viewed in ie11?

![image](https://user-images.githubusercontent.com/26335003/82614185-10e64d80-9b7c-11ea-843f-b0419ca6fdbb.png)

**Comment by qqnluaq** [comment]
interesting.. This is what I see when I open it in IE11:
![image](https://user-images.githubusercontent.com/20274603/82614354-80f4d380-9b7c-11ea-82cb-570a9d79a303.png)

**Comment by NicoledeGreef** [comment]
trns out mine was not displaying as nicely because IE 11 was set up to "run intranet sites in compatibility mode.  All good.
