### ISSUE TITLE
Disclaimer in Chrome, Firefox, and MS Edge on Windows 

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#143]
The Disclaimer that shows upon launch is not rendering as it was previously in Chrome, Firefox and MS Edge.  Seems to lack a scrollbar and therefore the entire contents is not within the white box.  

The difference is visible between Delivery and Production.

**Comment by qqnluaq** [comment]
odd. it works ok in chrome on a mac, but not on chrome on windows.
