### ISSUE TITLE
On screen legend pushes COVID symbology upwards and off screen

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#144]
When https://translink-d.apps.gov.bc.ca/trp/ starts up you can see all the symbols but one a waypoint is added the # of items in the  legend increases and the COVID related symbols are pushed upward and off the screen.  Unchecking layers contracts the list and symbols are once again visible.

Confirmed in Chrome and Firefox on Windows.  Wondering if a scroll bar in the legend might be feasible so that the user can get to all symbols if needed.

**Comment by NicoledeGreef** [comment]
verified on Desktop in Chrome, Firefox and Edge

**Comment by gk-tl** [comment]
Complete. Thank you.
