### ISSUE TITLE
COVID-19 Relief Schema Adjustment

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#146]
@qqnluaq I created the field 'ParkingSpaces' as a number field but it has become apparent that it is better suited to be a text field as there needs to be further description for vehicle size, types, etc.  Is it difficult to change the app so that is can accept the field 'ParkingSpaces' as text?

**Comment by qqnluaq** [comment]
nope, its easy

**Comment by al-tabb** [comment]
Awesome, thanks. Just to confirm, the field 'ParkingSpaces' will be text going forward.
