### ISSUE TITLE
Minor Truck Route Update

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#147]
@qqnluaq I have made some minor changes to the truck route network around the Tsawwassen ferry terminal.  The updated data is available here:
http://www.trp.regionalroads.com/api/?data=GM_TruckRoutes&format=geojson&download=true

**Comment by NicoledeGreef** [comment]
@qqnluaq -not sure if you were notified when this came in originally? we can do this data update if it's outstanding.

**Comment by qqnluaq** [comment]
I can do update now

**Comment by NicoledeGreef** [comment]
thank @qqnluaq

**Comment by gk-tl** [comment]
@al-tabb please confirm whether this ticket is complete.

**Comment by al-tabb** [comment]
This is not yet complete.  The truck routes around the Tsawwassen Ferry Terminal should look like this (screenshot of current GM_TruckRoutes dataset):
![image](https://user-images.githubusercontent.com/59742145/85339989-1647f800-b49a-11ea-8480-cd51188056fe.png)
Some roads inside the ferry terminal are still shown as truck routes in the app:
![image](https://user-images.githubusercontent.com/59742145/85340054-3b3c6b00-b49a-11ea-9b6a-83cb243bbd9c.png)

**Comment by NicoledeGreef** [comment]
@qqnluaq - can you please investigate?

**Comment by al-tabb** [comment]
Looks like this is completed in dev and test.  I was looking at production.
