### ISSUE TITLE
Bottom arrow in the scroll bar for the "layer" window is not working 

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#150]
Bottom arrow in the "layer" scroll bar is not working (same issue in dev/prod)

![Scrollbar](https://user-images.githubusercontent.com/59627982/83293775-160d5300-a1a1-11ea-94b5-ea479a9d9400.png)

**Comment by NicoledeGreef** [comment]
https://translink-t.apps.gov.bc.ca/trp/

Verified the issue in Chrome, Firefox, and Edge; if you click the arrow at the bottom of the scrollbar, it doesn't move the scrollbar down.  The scrollbar can be dragged, however.

By contrast, the new scrollbar on the legend is working fine.

**Comment by qqnluaq** [comment]
@NicoledeGreef  This issue is due to a feature in SMK that shows arrows at the top and bottom of a list when there is more content available off-screen, but thats only really useful on mobile devices. I can remove the SMK-generated arrows so the scrollbars function normally.

**Comment by NicoledeGreef** [comment]
looks good to me at https://translink-d.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Complete. Thank you.
