### ISSUE TITLE
TRN additions in Coquitlam

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#153]
@al-tabb please confirm whether COQ TRN updates will be ready for July 2 launch announcement.

**Comment by al-tabb** [comment]
Just completed this update.  I'll let Graeme know that the routing data set needs to be updated as well.
@qqnluaq @NicoledeGreef The updated data is available here: http://www.trp.regionalroads.com/api/?data=GM_TruckRoutes&format=geojson&download=true

**Comment by gk-tl** [comment]
Thank you.

**Comment by gleeming** [comment]
I just submitted a JIRA ticket for GeoBC to set truck routes in ITN on 32 segments of Mariner Way/Guildford Way/Johnson St.

**Comment by gk-tl** [comment]
Complete. Thank you.
