### ISSUE TITLE
Covid-19 Layer - Display of null values

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#154]
All fields with null values should not be displayed.  For example, portable toilet location data has null values for almost all fields. Fields that are populated (and should be displayed) are Name, AmenityType, AmenityLocation, OpenHours. All other fields (null values) should not be visible.

![Pic](https://user-images.githubusercontent.com/59627982/86048263-13528780-ba05-11ea-9bb0-6468a9dd2af5.png)

Note: Active field should not be visible despite being populated (as is already the case).

**Comment by gk-tl** [comment]
Additional note: this functionality should already be built into the UI (i.e., null = not displayed).

**Comment by al-tabb** [comment]
As a first step its probably worth trying a data refresh.  I don’t remember having these ‘No’ values in a previous version of the dataset but its been quite some time since we updated it so its possible that we did.  The data is available here: http://trp.regionalroads.com/api/?data=GM_Covid19Relief&format=geojson&download=true

**Comment by NicoledeGreef** [comment]
the data display is flexible; if you want to suppress null values you have to configure that for each layer.

@qqnluaq  - can you please look into this ?  @al-tabb has suggested that perhaps the latest data was not picked up.  that may solve the issue.

**Comment by qqnluaq** [comment]
There have been no changes to the COVID layers since the last time i loaded them (may 15).

**Comment by NicoledeGreef** [comment]
thanks for checking, @qqnluaq.  sounds like a configuration change to suppress null values is required then.

**Comment by qqnluaq** [comment]
changed app to not show attributes that did show 'No'

**Comment by NicoledeGreef** [comment]
looks good here:  https://bcgov.github.io/smk-tlink/
please review ASAP @gk-tl  and @al-tabb

**Comment by gk-tl** [comment]
@NicoledeGreef @qqnluaq Thank you. Looks good. -- Complete --
