### ISSUE TITLE
COVID-19 Relief Data Update

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#155]
@NicoledeGreef Is it possible to do a refresh of the data?  I've just done an update that has made some additional features inactive.  If it is possible to do this today that would be much appreciated.
http://trp.regionalroads.com/api/?data=GM_Covid19Relief&format=geojson&download=true
Tagging @gk-tl for awareness.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - some of the points in the CVOID layers have been de-activated for various reasons.  please update.

**Comment by qqnluaq** [comment]
done.

**Comment by NicoledeGreef** [comment]
thanks - verified some expected changes in https://translink-d.apps.gov.bc.ca/trp/
please review, @al-tabb

**Comment by NicoledeGreef** [comment]
@al-tabb - has this one been reviewed as well?

**Comment by al-tabb** [comment]
Yes, this looks good.  There is another update to the COVID-19 Relief dataset coming mid-week but this particular update is complete.  Thanks.
