### ISSUE TITLE
Advisory/Restriction Layers - Missing Advisory/Restriction Descriptions

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#157]
Latest version of the app in https://translink-d.apps.gov.bc.ca/trp/ is missing advisory/restriction descriptions

Example - border crossing info (advisory)

![image](https://user-images.githubusercontent.com/59627982/87209618-6101a680-c2c7-11ea-984b-993ca96378c9.png)

Example - Richmond restrictions

![image](https://user-images.githubusercontent.com/59627982/87209777-03218e80-c2c8-11ea-8d60-b38270519e38.png)

**Comment by gk-tl** [comment]
@al-tabb please double check that the latest version of the data is correct.

**Comment by qqnluaq** [comment]
looks a typo was introduced at tlink-147: https://github.com/bcgov/smk-tlink/commit/63f9bf1c6a64d97658760cee950407ee5d4b2a1b#diff-e7249089f75691850a0a398794fee120
`AdvisoryDescription` became `AdvisoryDesctiption` which broke the feature display

**Comment by al-tabb** [comment]
Strange... not sure how that happened.  The data is now corrected:
http://trp.regionalroads.com/api/?data=GM_TruckRoutes&format=geojson&download=true

**Comment by al-tabb** [comment]
I still don't see the AdvisoryDescription field in the app.  @qqnluaq Does the data look good on your end?
![image](https://user-images.githubusercontent.com/59742145/87458095-4af13000-c5be-11ea-819d-0bf960d5c4ef.png)

**Comment by NicoledeGreef** [comment]
The JSON in the application (https://translink-d.apps.gov.bc.ca/trp/layers/truck-advisories-restrictions/truck-advisories-restrictions.geojson) shows"AdvisoryDesctiption".  Looks like the latest data is not in Delivery yet. @qqnluaq - can you please incorporate the latest from the link provided above?

**Comment by qqnluaq** [comment]
looks ok to me:
![image](https://user-images.githubusercontent.com/20274603/87460421-b2f54580-c5c1-11ea-8e8b-a865ee6c7a30.png)

**Comment by gk-tl** [comment]
I just checked https://translink-d.apps.gov.bc.ca/trp/ and https://translink-t.apps.gov.bc.ca/trp/ - advisory/restriction info is missing.  The descriptions are visible in https://translink.apps.gov.bc.ca/trp/, but the data for the border crossings is dated.

**Comment by NicoledeGreef** [comment]
I had to use an incognito window but I now see the Advisory Description.  Alternatively one could clear browser history.

**Comment by gk-tl** [comment]
Confirming I can see the description info when I clear the browsing history in chrome. 

![image](https://user-images.githubusercontent.com/59627982/87463853-f7cfab00-c5c6-11ea-99c0-89ca923278bd.png)

**Comment by al-tabb** [comment]
Me too!

**Comment by NicoledeGreef** [comment]
after your review the data, please let me know if we are good to close this one.

**Comment by al-tabb** [comment]
Yes the data looks good now, feel free to close this.  Thanks.

**Comment by gk-tl** [comment]
Agree with @al-tabb . Good to go.

**Comment by NicoledeGreef** [comment]
thanks!
