### ISSUE TITLE
Remove link and reference to TRP feedback survey

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#158]
The checkbox survey is no longer appropriate given it refers to a "BETA" app. I think it's also redundant at this stage to provide a survey link and a feedback form. Suggest deleting top paragraph of text and replacing with "Use this form to email TransLink:"

![image](https://user-images.githubusercontent.com/59627982/87356643-3dcd3600-c517-11ea-9ab1-5becc5259031.png)

**Comment by NicoledeGreef** [comment]
@qqnluaq  - please action.

**Comment by gk-tl** [comment]
Complete. Thank you.
