### ISSUE TITLE
Disclaimer in Chrome and Firefox

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#16]
Beta ver: 0.0.2 built: 2019-12-20

The Disclaimer text is not totally readable in Firefox or Chrome on Windows 10.  No ability to scroll down to see it all.

**Comment by NicoledeGreef** [comment]
<img width="777" alt="truncated_disclaimer" src="https://user-images.githubusercontent.com/26335003/71385529-22abd080-259d-11ea-9a9f-f20c01a11ac3.PNG">

**Comment by gk-tl** [comment]
Complete. Thank you.
