### ISSUE TITLE
COVID-19 Relief Dataset Update

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#161]
@qqnluaq @NicoledeGreef @gk-tl 
The COVID-19 Relief dataset has been updated to reflect the following changes:
1. Added, removed, updated features based on current data from mealsfortruckers.ca
2. Refined locations of portable toilets to correspond to logical highway pullouts, etc.
3. Added several CVSE Inspection Stations based on this information: http://www.th.gov.bc.ca/CVSE_Mobile/InspectionStations/
4. Updated InformationLink and Comment fields to indicate relevant source of data (CVSE, Mealsfortruckers) and date of information capture.

The updated data is available here: http://trp.regionalroads.com/api/?data=GM_Covid19Relief&format=geojson&download=true

**Comment by NicoledeGreef** [comment]
@al-tabb @gk-tl 
the data update is in place in https://translink-d.apps.gov.bc.ca/trp/
please try an incognito window if you are not seeing the updates.

**Comment by al-tabb** [comment]
I can confirm that I'm seeing the updates.

**Comment by NicoledeGreef** [comment]
thanks - we've migrated the update to Test.  please review the app and data in Test and advise if we are good to migrate to Production:
https://translink-t.apps.gov.bc.ca/trp/

**Comment by al-tabb** [comment]
I've just spotted a small error in the data and quickly corrected it.  The link in the 'Comment' field for portable toilets was pointing to the pdf map as opposed to the CVSE 'Whats New' page.  I have corrected the data and it is available here:
http://trp.regionalroads.com/api/?data=GM_Covid19Relief&format=geojson&download=true
If possible it would be great to migrate this version instead.

**Comment by gk-tl** [comment]
al-tabb please double check that the portable toilet locations we previously commented out are "active". I think a couple are missing on Vancouver Island.

**Comment by gk-tl** [comment]
@al-tabb Portable toilet location Hwy 1 WB West of 176 Street does not appear to be correct. I think it should be further west, at the old weigh scale pullout:

https://www.google.ca/maps/place/49%C2%B011'09.2%22N+122%C2%B045'02.4%22W/@49.1858889,-122.7512139,243m/data=!3m2!1e3!4b1!4m6!3m5!1s0x0:0x0!7e2!8m2!3d49.1858863!4d-122.7506729?hl=en


![image](https://user-images.githubusercontent.com/59627982/87715993-03f06f80-c763-11ea-828b-321028ef08d7.png)

**Comment by al-tabb** [comment]
@gk-tl Changes complete.
http://trp.regionalroads.com/api/?data=GM_Covid19Relief&format=geojson&download=true

**Comment by gk-tl** [comment]
Thanks @al-tabb

**Comment by NicoledeGreef** [comment]
the latest data is now in https://translink-d.apps.gov.bc.ca/trp/ please review and advise if we are good to migrate it forward.

**Comment by gk-tl** [comment]
Please proceed to production. Thank you.

**Comment by NicoledeGreef** [comment]
data has been migrated to Test and Production:
https://translink-t.apps.gov.bc.ca/trp/
https://translink.apps.gov.bc.ca/trp/

**Comment by al-tabb** [comment]
Awesome, thanks Nicole.

**Comment by gk-tl** [comment]
@qqnluaq @NicoledeGreef @al-tabb many, many, many thanks to all of you for getting this done!
