### ISSUE TITLE
Line breaks in "Comments" field - COVID-19 Layer

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#163]
Creating a new ticket in case this is not a quick fix. If it is not, proceed to production and address in a future release.

Please add a line break for the "Data Source" text in the comments field. Not sure whether formatting like this is handled at the front-end or in the data set.

Example:

**_Special rates available for truck drivers and essential workers, call the hotel for more information. Free high-speed wireless internet and our restaurant offers delicious dining, where truck drivers and essential workers can take advantage of a 30% OFF* on their order (take out or pick up ONLY).
<line break / empty line>
Data Source: <line break>
Meals for Truckers Website (Link). Accessed on July 10, 2020._**

![image](https://user-images.githubusercontent.com/59627982/87717153-d3113a00-c764-11ea-99f8-e472d81eb465.png)

**Comment by NicoledeGreef** [comment]
@qqnluaq - this would be data side, correct?

**Comment by qqnluaq** [comment]
ya. it would. but if this data for the covid relief layer, it might be moot. (#185)
