### ISSUE TITLE
Portable Toilet Location Error

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#164]
@al-tabb please verify for post-launch update:

![image](https://user-images.githubusercontent.com/59627982/87730752-8ab24600-c77d-11ea-8c49-71f7a1ea7c59.png)

I believe this location is further west, as follows:

(Revised) Summit view point at Malahat summit on TCH NB: https://goo.gl/maps/rdiD4nWokabpW8uD8 (you can actually see the portable toilets in street view/satellite view).

**Comment by al-tabb** [comment]
Done.
