### ISSUE TITLE
Temporary Road Closures Data Update

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#168]
@NicoledeGreef There has been an addition to the temporary road closures datasets.  The updated datasets are available here:
http://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosuresExtent&format=geojson&download=true
http://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosures&format=geojson&download=true

Tagging @gk-tl for awareness.

Also a heads up that there may another small change occurring on July 31st (Mosquito Creek Closure becomes inactive).  We are just waiting to hear back from City of North Vancouver to confirm.

**Comment by al-tabb** [comment]
I can now confirm that the Mosquito Creek project has been extended by a month.  The data has been updated to reflect this change as well.

**Comment by gk-tl** [comment]
Thanks Alan.

**Comment by NicoledeGreef** [comment]
Data downloaded (July 30 @9:30am) and renamed to match application:
temporary-road-closure.geojson
temporary-road-closure-extent.geojson

**Comment by NicoledeGreef** [comment]
Compared data provided to schema documented in https://github.com/bcgov/smk-tlink/issues/128 and found the files to be a match.

**Comment by NicoledeGreef** [comment]
@al-tabb - please review in https://translink-d.apps.gov.bc.ca/trp/

**Comment by al-tabb** [comment]
The link is not displaying correctly.  Also, the text is being cut off by the identify window.
![image](https://user-images.githubusercontent.com/59742145/89064830-8d856d00-d31f-11ea-91bd-4a988cd2d18a.png)

**Comment by NicoledeGreef** [comment]
In light of this unexpected issue, passing ticket to @qqnluaq for investigation.

**Comment by qqnluaq** [comment]
done

**Comment by gk-tl** [comment]
Quick note: The old Front Street Closure Extent and Icon are now also visbile (status = inactive).

![image](https://user-images.githubusercontent.com/59627982/89078520-6a67b700-d339-11ea-921e-4f98d4327d8a.png)

The weekend/holiday closure for Summer 2020 looks good.

**Comment by qqnluaq** [comment]
removed inactive features.

**Comment by gk-tl** [comment]
Thank you.

**Comment by al-tabb** [comment]
This is now complete.  Thank you.

**Comment by gk-tl** [comment]
Confirming that it appears in https://translink-d.apps.gov.bc.ca/trp/ but not in test/prod.

![image](https://user-images.githubusercontent.com/59627982/91071657-51c38780-e5ed-11ea-815e-c7c4fc55e303.png)

**Comment by NicoledeGreef** [comment]
It looks like this was not migrated to Test.  I will do that now.

**Comment by NicoledeGreef** [comment]
@gk-tl , @al-tabb please review in Test: https://translink-t.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Looks good. Thanks Nicole.

**Comment by NicoledeGreef** [comment]
Migrated to https://translink.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Perfect. Thank you.
