### ISSUE TITLE
Disclaimer in Chrome and Safari on iPhone 8

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#17]
Text on the Disclaimer accept button is truncated vertically

**Comment by NicoledeGreef** [comment]
![disclaimer_button_txt](https://user-images.githubusercontent.com/26335003/71386594-d1eba600-25a3-11ea-9520-443cdff375aa.jpg)

**Comment by gk-tl** [comment]
Confirming the text is not truncated on iPhone 6 Plus. Do not have access to iPhone 8.

**Comment by NicoledeGreef** [comment]
Confirming iPhone 8.
