### ISSUE TITLE
De-activate Mosquito Creek Bridge Replacement Closure as of Sep 8, 2020

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#172]
@al-tabb and @NicoledeGreef - please de-activate the Mosquito Creek Bridge Replacement Closure in North Vancouver.  The City is flipping traffic to the new structure in the evening on Sep 8.  Trucks will no longer be required to use the detour route. 

It would be great if the TRP cartographic layers "Temporary Road Closures" and "Temporary Road Closures Extent" could be updated and pushed to production on Sep 9. 

![image](https://user-images.githubusercontent.com/59627982/91884470-ee63d600-ec3a-11ea-8ef3-d30206d24c1d.png)

**Comment by NicoledeGreef** [comment]
@al-tabb please advise when data updates are ready to download.

**Comment by NicoledeGreef** [comment]
The latest Temporary Road Closures and TRC Extents data has been moved to Delivery.  Please review:
https://translink-d.apps.gov.bc.ca/trp/

**Comment by al-tabb** [comment]
Looks good, thanks.

**Comment by NicoledeGreef** [comment]
has been migrated to Prod:
https://translink.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Thank you.
