### ISSUE TITLE
De-activate Front Street Closure as of Sep 7, 2020

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#173]
@al-tabb and @NicoledeGreef Please de-activate the closure notice for Front Street in New Westminster.  the weekend closures of Front Street are set to expire as of 8 pm on Sep 7.  

It would be great if the TRP cartographic layers "Temporary Road Closures" and "Temporary Road Closures Extent" could be updated and pushed to production **on Sep 9**. Update timing aligns with ticket  #172 

![image](https://user-images.githubusercontent.com/59627982/91885381-8615f400-ec3c-11ea-8ed6-8857b1dc319c.png)

**Comment by NicoledeGreef** [comment]
@al-tabb please advise when data updates are ready to download.

**Comment by al-tabb** [comment]
Datasets have been updated: 
https://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosures&format=geojson&download=true
https://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosuresExtent&format=geojson&download=true

**Comment by NicoledeGreef** [comment]
The latest Temporary Road Closures and TRC Extents data has been moved to Delivery.  Please review:
https://translink-d.apps.gov.bc.ca/trp/

**Comment by al-tabb** [comment]
The Status = 'Inactive' closures are still showing (Mosquito Creek, Front St and Front St @ Begbie and Columbia).

**Comment by al-tabb** [comment]
Looks good now, thanks.

**Comment by NicoledeGreef** [comment]
Has been migrated to Test; please review:
https://translink-t.apps.gov.bc.ca/trp/

**Comment by NicoledeGreef** [comment]
has been migrated to Prod: https://translink.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Thank you.
