### ISSUE TITLE
Provincial Highways Layer - Change Filter

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#174]
I've just noticed that the current filter applied to produce the 'Provincial Highway' layer leaves out a few segments.  This is because we were forced to classify a few Provincial Highway segments as restrictions (Lions Gate Bridge, Queensborough Bridge, some border segments)

What is the level of effort to change the filter to ProvincialJurisdiction = 1

This change would allow the dataset to include all of the appropriate segments including the restricted segments.

**Comment by NicoledeGreef** [comment]
Has been migrated to Test; please review:
https://translink-t.apps.gov.bc.ca/trp/

**Comment by NicoledeGreef** [comment]
This also went to Prod on Sept 8
https://translink.apps.gov.bc.ca/trp/
