### ISSUE TITLE
Add Granville, Seymour, and Lonsdale Temp Partial Road Closures to Cartographic Layers

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#175]
@al-tabb and @NicoledeGreef  please update TRP cartographic layers "Temporary Road Closures" and "Temporary Road Closures Extent" with the following road closures:

1. Temporary Partial Road Closure: Granville Street Curb Lanes Closed until October 31, 2020 (All hours of the day)
2. Temporary Partial Road Closure: Seymour Street Curb Lane Closed until October 31, 2020 (All hours of the day)
3. Temporary Partial Road Closure: Lonsdale Avenue Curb Lanes Closed until October 31, 2020 (All hours of the day)

See word file for closure description and dates:

[2020-09-02 TRP Temp Closures.docx](https://github.com/bcgov/smk-tlink/files/5164441/2020-09-02.TRP.Temp.Closures.docx)

Timing can coincide with tickets #172 and #173 (i.e., Sep 9, 2020).

**Comment by al-tabb** [comment]
These changes are included in the data update for tickets #172 & #173 

https://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosures&format=geojson&download=true
https://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosuresExtent&format=geojson&download=true

**Comment by NicoledeGreef** [comment]
The latest Temporary Road Closures and TRC Extents data has been moved to Delivery.  Please review:
https://translink-d.apps.gov.bc.ca/trp/

**Comment by al-tabb** [comment]
My apologies, I used the wrong link for the Lonsdale closure.  The data has been corrected:
https://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosures&format=geojson&download=true
https://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosuresExtent&format=geojson&download=true

**Comment by al-tabb** [comment]
This looks good, thanks.  Unless @gk-tl chimes in, we are good to go for the September 9th update.

**Comment by NicoledeGreef** [comment]
Has been migrated to Test; please review:
https://translink-t.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
@al-tabb please update the Lonsdale closure name as per word file linked above.

Current text in test:
Temporary Lonsdale Avenue Curb Lanes Closure from now until October 31, 2020 (All hours of the day)

Text from word file:
Temporary Partial Road Closure: Lonsdale Avenue Curb Lanes Closed until October 31, 2020 (All hours of the day)

Otherwise, all looks in order. Thank you everyone.

**Comment by al-tabb** [comment]
This is now complete.  The Seymour road closures also needed the title updated.
https://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosures&format=geojson&download=true
https://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosuresExtent&format=geojson&download=true

**Comment by gk-tl** [comment]
@al-tabb thanks for catching that. 

@NicoledeGreef good to go to production with the noted changes to the closure names for the Seymour & Lonsdale temp closures.

Thank you.

**Comment by NicoledeGreef** [comment]
Sept 4 changes are now in Production: https://translink.apps.gov.bc.ca/trp/ 

September 8 changes are now in Delivery: https://translink-d.apps.gov.bc.ca/trp/ 
Please review and advise if good to migrate to Test.

**Comment by gk-tl** [comment]
Sep 4 changes - thank you.

Sep 8 changes - reviewed in delivery. Looks good. Thank you..

**Comment by NicoledeGreef** [comment]
Thanks - changes are now in Test: https://translink-t.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Looks good. Thank you.

**Comment by NicoledeGreef** [comment]
Thanks - changes are now in Production: https://translink.apps.gov.bc.ca/trp/
