### ISSUE TITLE
New Temporary Road Closures

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#182]
We have had two additional Temporary Road Closures come in.  Here is updated data:
http://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosuresExtent&format=geojson&download=true
http://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosures&format=geojson&download=true

If we could perform the update this week or next week that would be great.

Tagging @gk-tl for awareness.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - could you please incorporate these data updates into Delivery as soon as possible?

**Comment by al-tabb** [comment]
Thanks Nicole.  @qqnluaq There was a small change needed and I just pushed a new update to production as of 3:30pm today.  Please ensure that the version used was downloaded after that time.

**Comment by qqnluaq** [comment]
got it

**Comment by NicoledeGreef** [comment]
thanks @qqnluaq!

@al-tabb @gk-tl  please review in  https://translink-d.apps.gov.bc.ca/trp/ 
clearing your browser cache or trying incognito may be necessary at first in order to pick up the change

**Comment by gk-tl** [comment]
@al-tabb please double check our source data for the E. Columbia Street temp closure, which  is expected to be in effect until late November.

Closure Description
From early August to **late** November 2020 there will be a rolling full road closure on East Columbia Street between...

End date:
**2020-11-30 23:59:00**

![image](https://user-images.githubusercontent.com/59627982/94967719-77796180-04b4-11eb-9c80-33960226bca5.png)

**Comment by al-tabb** [comment]
Looks like that edit was made in the point dataset but not the polygon dataset.  I'll update it now.

**Comment by al-tabb** [comment]
OK, data has been updated and is now good to go: http://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosuresExtent&format=geojson&download=true

@gk-tl There was a bug in our update app that wasn't recognizing the polygon geometry type.  This is why your edits did not go through.  I fixed it and now everything should work as expected.

**Comment by gk-tl** [comment]
Thanks Alan.

**Comment by NicoledeGreef** [comment]
@qqnluaq there is a new update for incorporation when you can.

**Comment by qqnluaq** [comment]
done

**Comment by gk-tl** [comment]
Looks good. Thank you.

**Comment by NicoledeGreef** [comment]
@gk-tl this is now in Test.  please review: https://translink-t.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Reviewed in test. Looks good. Thank you.

**Comment by NicoledeGreef** [comment]
Thanks - this update has now been migrated to Production: https://translink.apps.gov.bc.ca/trp/
