### ISSUE TITLE
Remove Covid-19 Relief Layer

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#185]
Please remove the Covid-19 Relief Layer from the map.  This includes removing it as an option from the layer list and removing it from the legend as well.

**Comment by NicoledeGreef** [comment]
@al-tabb @gk-tl this change is now in place at: https://translink-d.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Thank you. Good to go.

**Comment by NicoledeGreef** [comment]
please review in Test: https://translink-t.apps.gov.bc.ca/trp/

**Comment by al-tabb** [comment]
Looks good. Thank you.

**Comment by NicoledeGreef** [comment]
migrated to Production

**Comment by gk-tl** [comment]
Thank you.
