### ISSUE TITLE
Update to Truck Routes Layer

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#186]
I have just completed a small update to the truck routes layer which removes some ramps from Knight St.  The updated data is available here:
http://trp.regionalroads.com/api/?data=GM_TruckRoutes&format=geojson&download=true

**Comment by NicoledeGreef** [comment]
@al-tabb @gk-tl this change is now in place at: https://translink-d.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
@al-tabb please confirm the update. Looks good to me.

**Comment by al-tabb** [comment]
Looks good to me too.

**Comment by NicoledeGreef** [comment]
please review in Test: https://translink-t.apps.gov.bc.ca/trp/

**Comment by al-tabb** [comment]
Looks good.  Thanks.

**Comment by NicoledeGreef** [comment]
migrated to Production

**Comment by gk-tl** [comment]
Thank you.
