### ISSUE TITLE
Chrome Developer Tools Recommends Disabling Debug Mode Before Production Deployment

### ISSUE THREAD

**Issue by gjlawran** [bcgov/smk-tlink#189]
When I load https://translink.apps.gov.bc.ca/trp/ - I see a warning from Google Chrome Developer tools Console that suggests that we are running Vue in development mode and that we should change to production mode prior to deployment.  Not sure if this is important.

![image](https://user-images.githubusercontent.com/1154765/100146801-4c294800-2e4f-11eb-98ed-a329a8641a02.png)

**Comment by qqnluaq** [comment]
its harmless.
