### ISSUE TITLE
Advisory descriptions missing.

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#191]
@al-tabb and @NicoledeGreef

Advisory description text is missing from all layers.

Example:
![image](https://user-images.githubusercontent.com/59627982/104490567-d788a500-5585-11eb-9048-ed1ca5abfdf3.png)

**Comment by NicoledeGreef** [comment]
i believe this has occurred because the field name supplied in the data downloaded from regionalroads.com Geoserver does not match the model as defined in #128;  "AdvisoryDesctiption" should be "AdvisoryDescription"

we can search/replace this within the application data file but please correct it at the source as well.

**Comment by NicoledeGreef** [comment]
This has been addressed in Delivery: https://translink-d.apps.gov.bc.ca/trp/

![image](https://user-images.githubusercontent.com/26335003/104641701-f9098f80-565e-11eb-90e7-f54b772874f9.png)

Please confirm and we'll move it to Test and Prod.

**Comment by gk-tl** [comment]
Thanks @NicoledeGreef. Reviewed in delivery. Looks good.

**Comment by NicoledeGreef** [comment]
The update has been migrated to Test and Production.

https://translink-t.apps.gov.bc.ca/trp/
https://translink.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Thank you. This ticket is complete.

**Comment by al-tabb** [comment]
> i believe this has occurred because the field name supplied in the data downloaded from regionalroads.com Geoserver does not match the model as defined in #128; "AdvisoryDesctiption" should be "AdvisoryDescription"
> 
> we can search/replace this within the application data file but please correct it at the source as well. @al-tabb

This has now been corrected.
