### ISSUE TITLE
Updated Temporary Road Closures Dataset

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#195]
There is an update available for the Temporary Road Closures & Temporary Road Closures Extent datasets.

I have made some changes to the data pipeline on my end and as a result the fields 'Shape_Area' and 'Shape_Length' are no longer generated for Temporary Road Closures Extent.  Is this an issue?  I don't think that these fields were utilized in any way on the front end.  This is the revised schema:
"GM_TemporaryRoadClosuresExtent" [ "ClosureDescription", "ClosureName", "EndDate", "Link", "Notes",  "StartDate", "Status" ]

Let me know if this is a problem and I can come up with a workaround.

The updated datasets are available here:
https://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosures&format=geojson&download=true
https://trp.regionalroads.com/api/?data=GM_TemporaryRoadClosuresExtent&format=geojson&download=true

*These are both intentionally empty datasets as we currently have no active temporary road closures.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - is there any impact here?

**Comment by al-tabb** [comment]
This looks good to me in delivery.

**Comment by NicoledeGreef** [comment]
migrated to Test and Prod:

https://translink-t.apps.gov.bc.ca/trp/
https://translink.apps.gov.bc.ca/trp/
