### ISSUE TITLE
Disclaimer not displaying properly in Google Chrome (Desktop)

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#196]
@NicoledeGreef I also checked MS Edge and Firefox (Desktop) and Google Chrome & Safari on iOS (iPhone 8+). No issues. Seems to be isolated to Google Chrome desktop.

![image](https://user-images.githubusercontent.com/59627982/107600817-b7c2bc00-6bd9-11eb-938f-754e05f85618.png)

**Comment by NicoledeGreef** [comment]
Upon Inspection of the disclaimer dialog in Chrome v88, I see:

```
dialog {
    top: 50%;
    left: 50%;
    width: 90%;
    height: 90%;
    max-width: 50em;
    max-height: 55em;
    transform: translateY(-50%) translateX(-50%);
    font-family: "Meta W01 Medium", Arial, Helvetica, sans-serif;
    z-index: 3;
    padding: 0;
    border: none;
    min-height: auto;
}
```

if I adjust  transform: translateY(-50%) to (-25%) it is placed better on the screen.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - this is a UI bug introdcued by Chrome update (no changes occurred in the codebase for some time).

**Comment by gk-tl** [comment]
Here's what I'm now seeing in dev when using Chrome and now also Edge.

![image](https://user-images.githubusercontent.com/59627982/109375802-6a4e7c00-7874-11eb-9556-d1c060482212.png)

**Comment by qqnluaq** [comment]
should be fixed now

**Comment by gk-tl** [comment]
Indeed. All looks good now. Thank you @qqnluaq

**Comment by NicoledeGreef** [comment]
fixes deployed to test and Prod:

https://translink-t.apps.gov.bc.ca/trp/
https://translink.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
@NicoledeGreef & @qqnluaq - thank you!
