### ISSUE TITLE
TRP Disclaimer not displaying in Chrome for iOS

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#205]
@NicoledeGreef - disclaimer not shoring on iPhone 8 Plus - Chrome

![file](https://user-images.githubusercontent.com/59627982/120539462-7595d400-c39c-11eb-97ec-e40f9244e11c.jpeg)

**Comment by NicoledeGreef** [comment]
hi @gk-tl  - do you use this configuration regularly? i'm wondering if is this a new development and what version of iOS and Chrome you are running.

**Comment by NicoledeGreef** [comment]
confirmed this is also an issue on my iPhone 8 using both Chrome and Safari running on iOS 14.4.2

**Comment by gk-tl** [comment]
@NicoledeGreef - I tend to use the TRP on my desktop, but occasionally refer to it on my mobile. Running the latest version of iOS (14.6). Chrome version 90.0.4430.216.

**Comment by NicoledeGreef** [comment]
confirmed on iOS 14.6 on iPhone as well.
@qqnluaq  - can you please investigate this issue?

**Comment by NicoledeGreef** [comment]
i have confirmed this is fixed on my iPhone in Chrome and Safari.

**Comment by gk-tl** [comment]
@NicoledeGreef confirming the disclaimer works as intended in test. Thank you.

**Comment by NicoledeGreef** [comment]
update is now in Production. you may need to use an incognito/private window to see the changes.

https://translink.apps.gov.bc.ca/trp/
