### ISSUE TITLE
Truck Routes Dataset Update

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#206]
Hi @NicoledeGreef 

We've had some bylaw changes and as a result I have updated the Truck Routes dataset.  The updated data is available here:

https://api.regionalroads.com/simplewfs/?service=WFS&version=1.0.0&request=GetFeature&typeName=GM_TruckRoutes&outputFormat=application/json&download=true

@gk-tl

**Comment by NicoledeGreef** [comment]
thanks @al-tabb

**Comment by NicoledeGreef** [comment]
@qqnluaq  - i think this is a file that needs further processing in order to be integrated with the application?  i checked the attribute names and they are as expected.

**Comment by NicoledeGreef** [comment]
hi @qqnluaq  - would you please action this ticket as soon as you can?

**Comment by NicoledeGreef** [comment]
@al-tabb the data is now in Delivery and Test for your review:
https://translink-d.apps.gov.bc.ca/trp/
https://translink-t.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
@al-tabb The latest data appears to be reflected accurately in test (eg COB truck def = 11,800 kg). Please confirm that everything checks out so that the changes can be promoted and the ticket can be closed (thank you in advance).

**Comment by NicoledeGreef** [comment]
@al-tabb any concerns about us moving this one to Production?

**Comment by al-tabb** [comment]
Looks good to me, thanks.

**Comment by NicoledeGreef** [comment]
update is now in Production.  you may need to use an incognito/private window to see the changes.

https://translink.apps.gov.bc.ca/trp/
