### ISSUE TITLE
Legend - Display "Potential Route" & "Unverified Route"

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#21]
It would be great if the legend contained an entry for the generated route which indicates the difference between the proposed portion of the route and the unverified portion of the route.  

CVRP BETA Screenshot:
![image](https://user-images.githubusercontent.com/59627982/72028035-0a42e380-3236-11ea-9972-ad73f3cd24fa.png)

**Comment by qqnluaq** [comment]
At the moment there is no way to see the route on the map at the same time as the legend.

**Comment by NicoledeGreef** [comment]
"Potential Route" was previously known as "Proposed Route"

**Comment by NicoledeGreef** [comment]
Re: "At the moment there is no way to see the route on the map at the same time as the legend."
related to:
https://github.com/bcgov/smk-tlink/issues/18
https://github.com/bcgov/smk-tlink/issues/34

**Comment by gk-tl** [comment]
Complete. Thank you.
