### ISSUE TITLE
Geoserver and security on layers

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#211]
Re: accessing layers directly from Translink's Geoserver instances, there are basically two options:

1.	Public datasets only
a.	All datasets will be public access
b.	No token is required to access

2.	Public / private datasets
a.	Datasets can be private (overhead structures may fall into this category) or public
b.	To access private datasets would require a regional roads account; Token must be retrieved from https://api.regionalroads.com/token/
This API call must be made as a POST request from a back end resource as it requires a username / password which must be kept secret
POST Body
{"userName": jondoe@example.ca,
"password": "Fakepassword123"}
API Response
{
    "token": "faketoken123",
    "expires": "2021-12-21T18:48:33+00:00"
}
Token is then used to access private datasets from the API
When the current date/time is greater than the token expiry a new token must be retrieved
 
Option 2 would provide Translink with more flexibility.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - please review, ask any clarification questions and provide ballpark estimate

**Comment by qqnluaq** [comment]
Option 1: this would have no impact on estimate for #204, no additional work.

Option 2: there would be changes on the client side to retrieve the token at startup and possibly refresh it periodically. This would be no more than 1 days work for the client side code, otherwise #204 is unaffected.
There is also the work to write a back-end service to talk to the token API. This could be Java servlet or a Node service, or something else. Depends on how the application is being served at the moment.

**Comment by NicoledeGreef** [comment]
Thanks for the Option 2 order of magnitude estimate, @qqnluaq.  

Follow on question: the back-end service you mention would be developed/hosted by Translink?

**Comment by qqnluaq** [comment]
The back-end service would have to be hosted at the same place as the app, as this service has to provide the token to the app at startup

**Comment by al-tabb** [comment]
@qqnluaq Do you have an estimate for the back-end service work?

**Comment by qqnluaq** [comment]
I can't give a very accurate estimate. It seems to be a fairly simple task, but im not sure how it would be tied into the webserver, and get invoked when the application is requested. @NicoledeGreef do you know of any apps that do something similar?
My estimate would be 3 days, with very large error bars.

**Comment by NicoledeGreef** [comment]
thanks @qqnluaq - i'll schedule a meeting to discuss further.

**Comment by NicoledeGreef** [comment]
Meeting Conclusion: making secured data available in a public app is clunky and non-trivial.  a public view of the data will be made accessible via Geoserver instead.
