### ISSUE TITLE
Temporary Road Closure Data Update

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#214]
Hi @NicoledeGreef 

I have two layers that need updating:

GM_TemporaryRoadClosures
https://api.regionalroads.com/simplewfs/?service=WFS&version=1.0.0&request=GetFeature&typeName=GM_TemporaryRoadClosures&outputFormat=application/json&download=true
GM_TemporaryRoadClosuresExtent
https://api.regionalroads.com/simplewfs/?service=WFS&version=1.0.0&request=GetFeature&typeName=GM_TemporaryRoadClosuresExtent&outputFormat=application/json&download=true
 
Hopefully this will be the last manual data update.

**Comment by NicoledeGreef** [comment]
Thanks Al!

**Comment by NicoledeGreef** [comment]
The layers have been updated in the delivery version of the app: https://translink-d.apps.gov.bc.ca/trp/
Please review and let us know if it is fine to migrate the changes forward.

**Comment by al-tabb** [comment]
I just realized that the timezone issue I've mentioned previously will cause the dates/times to display incorrectly (well they are correct they're just in UTC).  I made a quick fix by doing the timezone conversion in the postgres views.  If you download the datasets again they should show the correct dates/times.

**Comment by NicoledeGreef** [comment]
timestamp updates are now in Delivery.  you may need to disable cache in your browser to pick up the changes:
https://translink-d.apps.gov.bc.ca/trp/

**Comment by al-tabb** [comment]
Looks good, ready to push to prod.  Thanks Nicole.

**Comment by NicoledeGreef** [comment]
This update has now been migrated to Test and Production.
https://translink-t.apps.gov.bc.ca/trp/ 
https://translink.apps.gov.bc.ca/trp/
