### ISSUE TITLE
App Name - Change to Truck Route Planner (TRP)

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#22]
Please change the App's name from Commercial Vehicle Route Planner (CVRP) to **Truck Route Planner (TRP)**. 

Aligns with MoTI preferences, and should reduce confusion for end users by clearly identifying the TL App as separate/distinct from the DriveBC Height Clearance Tool, which was at one point called the CVRP. 

Thank you in advance.

**Comment by cpspicer** [comment]
Closing - looks complete.

**Comment by gk-tl** [comment]
Confirming it's complete. Thank you.
