### ISSUE TITLE
Popups not showing for Provincial Highways

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#224]
I've just noticed a bug where popups do not show for Provincial Highways in the Truck Routes layer.  It seems to be isolated to this one sub-type within the Truck Routes layer and all others (e.g. Designated Municipal Truck Routes) are working fine.

**Comment by dgboss** [comment]
Thanks for bringing this to our attention. I looked at an older version of the app and saw the same behaviour. I'll look into this issue in our next sprint which starts tomorrow.

**Comment by dgboss** [comment]
@al-tabb querying/identifying was explicitly turned off via configuration for the truck-routes-provincial-highway-high-zoom and truck-routes-provincial-highway layers. If I enable query/identify features will be found and displayed, but every attribute of the feature will be displayed. Is this okay? Or would you prefer that only a subset of the attributes be visible?

This is the current view with all attributes visible:
![image](https://user-images.githubusercontent.com/7094320/170369081-40155de9-b9b0-4ce6-b8be-1daed9301578.png)

**Comment by dgboss** [comment]
@al-tabb I've enabled identify on the Truck Routes Provincial Highways layer, configured the attributes to display as requested and pushed the changes to delivery. Please take a look at your convenience and let me know if you would like any changes.

**Comment by al-tabb** [comment]
This looks good, thanks!

**Comment by dgboss** [comment]
@al-tabb I've pushed the update to the test environment. It looks good from my perspective, but please let me know when you would like to proceed with deployment to production. Thanks!

**Comment by al-tabb** [comment]
Looks good to me as well.  Feel free to deploy to production whenever you get a chance.  Thanks.

**Comment by dgboss** [comment]
The fix is now live in production. I smoke tested the fix and other functionality and all seems well.
