### ISSUE TITLE
Generate Multiple Route Options

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#23]
Depending on the level of effort, it would be helpful if the app could generate and display at least one alternate route (ideally two). This would apply to a "Proposed Route" (blue) and "Unverified Route" (dotted red line).

The rationale for this feature is to clearly communicate to the user that the app is generating proposed or unverified routes (as applicable) with the explicit expectation that the carrier and/or driver will choose a preferred route (at their sole discretion), and that they are responsible for verifying all clearances and restrictions on the route of their choice.

Example - Google Maps (and other Apps) provide up to 3 options: 
![image](https://user-images.githubusercontent.com/59627982/72114921-0aa4b280-32fa-11ea-8823-7ec7d5745aa1.png)

Note: The TL BETA does not generate multiple route options.

**Comment by qqnluaq** [comment]
There is a one possible to way to implement this: sometimes the route generated is different when the start & finish are reversed.

**Comment by al-tabb** [comment]
I think that the app should produce alternatives in every case.  This would communicate that these are 'proposed routes' and make it clear that each generated route is a suggestion .  It would also be great if all three suggested routes were displayed in the same way initially and the user was prompted to select one based on their preferences.  This again reinforces that the 3 generated routes are all suggestions.  I have two potential options to suggest:

1) Produce alternative costs
    The beta currently defines the cost of each segment as a combination of the truck route type, road type and segment length.  Truck routes are of course the lowest cost while there is a hierarchy of costs associated with the road type with freeways having the lowest cost.  The cost is slightly higher for highways, slightly higher again for arterials and so on.  One alternative would be to move the freeways highways down in the hierarchy so that arterials have the lowest cost.  This should produce alternate routes in many cases.

2) Removal of random segment
After generating the first route, requery the API for a new route with a random segment from the first route removed from the network (not the first or last segment).  This is actually how the beta currently routes around height restrictions (by removing the segment(s) with relevant height restrictions) and should produce alternative routes as well.

**Comment by cpspicer** [comment]
Will have scope/time/cost impact.  Need to discuss with client to initiate estimate & in-scope.  Should discuss on status call.

**Comment by NicoledeGreef** [comment]
Moved to Icebox as Alex R. conveyed this is no longer on the table.

**Comment by gk-tl** [comment]
Agreed. Thank you.
