### ISSUE TITLE
Identify data - visible attributes

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#24]
submitted by @al-tabb 

Is it possible to use the classic popup style box above the clicked on feature when identifying features?  This would probably only work well in a desktop environment.
![image](https://user-images.githubusercontent.com/59742145/72187387-5d3ea700-33ac-11ea-8bf8-a3ba71b3e691.png)

**Comment by NicoledeGreef** [comment]
I'm going to break this one into distinct Issue tickets: one for Legend / Route Planner 'Widget' Placement and Behaviour, one for Legend Items Modification, and one for Identify Tool.

**Comment by NicoledeGreef** [comment]
Created https://github.com/bcgov/smk-tlink/issues/33 and https://github.com/bcgov/smk-tlink/issues/34

**Comment by NicoledeGreef** [comment]
For identified values, if value = 'N/A' or number fields = null
Suppress SHAPE, LENGTH, Restricted, etc.

Al  to supply screen shots of identified layer attributes.

**Comment by al-tabb** [comment]
Truck Routes Layer (includes Provincial Highway, Designated Municipal Truck Route, Designated Municipal Truck Route with Restriction, Municipal Road with No Truck Restrictions, Federal Road with No Truck Restrictions)

![image](https://user-images.githubusercontent.com/59742145/73198882-b1ee5b80-40e8-11ea-955d-9ea101ba73d0.png)

**Comment by al-tabb** [comment]
Truck Advisories and Restrictions

![image](https://user-images.githubusercontent.com/59742145/73198975-dfd3a000-40e8-11ea-8a0d-327b6203be89.png)

Edit: Add 'Bylaw Link Field', add 'Notes' field

**Comment by al-tabb** [comment]
Overhead Structure with Height Marker

![image](https://user-images.githubusercontent.com/59742145/73199110-17dae300-40e9-11ea-9a51-1d2601eee3ed.png)

**Comment by al-tabb** [comment]
Overhead Structure without Height Marker

![image](https://user-images.githubusercontent.com/59742145/73199205-3e008300-40e9-11ea-8657-2c6a0551b083.png)

Edit: add 'Notes' field

**Comment by al-tabb** [comment]
Overhead Directional Sign

![image](https://user-images.githubusercontent.com/59742145/73199252-56709d80-40e9-11ea-9194-479c6049b6a0.png)

Edit: add 'Notes' field

**Comment by al-tabb** [comment]
Inspection Stations

![image](https://user-images.githubusercontent.com/59742145/73199329-7e600100-40e9-11ea-9d27-b9a03ced8276.png)

Edit: add 'Notes' field

**Comment by al-tabb** [comment]
Cardlock

![image](https://user-images.githubusercontent.com/59742145/73199368-946dc180-40e9-11ea-82b5-53a80eb0535e.png)

Edit: add 'Notes' field

**Comment by al-tabb** [comment]
Port of Vancouver Facilities / Terminals

![image](https://user-images.githubusercontent.com/59742145/73199455-ba936180-40e9-11ea-8e4a-448bd0577e55.png)

Edit: add 'Notes' field

**Comment by al-tabb** [comment]
Metro Vancouver Boundary

![image](https://user-images.githubusercontent.com/59742145/73199632-09d99200-40ea-11ea-8225-2472feea835d.png)

**Comment by al-tabb** [comment]
Truck Parking
![image](https://user-images.githubusercontent.com/59742145/73199663-1958db00-40ea-11ea-92af-c98028f4bb79.png)

Edit: add 'Notes' field

**Comment by al-tabb** [comment]
Layers without popups:
Industrial Area, Downtown Vancouver, Major Road Network, Provincial Highway

**Comment by gk-tl** [comment]
If not too late, please change “Truck Weight Definition” to “Heavy Truck Definition (LGVW)”

![](https://user-images.githubusercontent.com/59742145/73198882-b1ee5b80-40e8-11ea-955d-9ea101ba73d0.png)

In the notes field, please add text:

“A heavy truck, which is defined as a vehicle with a licensed gross vehicle weight (LGVW) greater than the weight specified above, must use truck routes for through-travel between the origin and destination. Heavy trucks are permitted to travel off truck routes for local pick-up and delivery, but must use the shortest distance between the truck route and the origin or destination.”

**Comment by qqnluaq** [comment]
> Truck Advisories and Restrictions
> Edit: Add 'Bylaw Link Field', add 'Notes' field

I don't see a Notes field:
```
FID: 1372
Bylaw_Link: "https://westvancouver.ca/sites/default/files/bylaws/TrafficandParkingBylawNo.4370%2C2004.pdf#page=26"
Provincial: 0
Designated: 0
Docu_PgNum: "Pg. 23 - 24, 37 - 38"
PDF_Page: "Pg. 26 - 27, 40 - 41"
City: "West Vancouver"
RGN: "GVRD"
Restricted: 1
Type: "Truck Travel Restriction or Prohibition"
TruckDefWt: 10000
Bylaw: "No. 4370, 2004, Pt. 8.16"
AdviseType: "Restriction"
Shape_Leng: null
AdviseDesc: "Trucks, Trailers or Truck-Tractor combinations in excess of 10,000kg GVW are prohibited in a downhill direction. For this road, travelling southbound is prohibited"
SHAPE__Length: 1133.27777844219
```

**Comment by gk-tl** [comment]
@al-tabb indicated adding a "notes" field as an edit:

> Truck Routes Layer (includes Provincial Highway, Designated Municipal Truck Route, Designated Municipal Truck Route with Restriction, Municipal Road with No Truck Restrictions, Federal Road with No Truck Restrictions)
> 
> ![image](https://user-images.githubusercontent.com/59742145/73198882-b1ee5b80-40e8-11ea-955d-9ea101ba73d0.png)
> 
> **Edit: add 'Notes' field**

**Comment by NicoledeGreef** [comment]
Notes was not supplied in the data, I think, unless that is the AdviseDesc field.  
Is it being requested that we add Notes to the data? Ideally, Translink will supply the data with all fields defined so that going forward the model will be consistent.

**Comment by gk-tl** [comment]
Followed up with @al-tabb . The "notes" field is already in the GeoDatabase (currently a null value/blank). However, Alan suggested that it would be best if he updates the file and re-submits with the changes below: 

> If it's not too late, please change “Truck Weight Definition” to “Heavy Truck Definition (LGVW)”
> 
> ![](https://user-images.githubusercontent.com/59742145/73198882-b1ee5b80-40e8-11ea-955d-9ea101ba73d0.png)
> 
> In the notes field, please add text:
> 
> “A heavy truck, which is defined as a vehicle with a licensed gross vehicle weight (LGVW) greater than the weight specified above, must use truck routes for through-travel between the origin and destination. Heavy trucks are permitted to travel off truck routes for local pick-up and delivery, but must use the shortest distance between the truck route and the origin or destination.”

**Comment by qqnluaq** [comment]
Temporary Road Closure Extent & Temporary Road Closure aren't mentioned here

**Comment by qqnluaq** [comment]
### Layers that where I was requested to add a Notes attribute but one doesn't seem to exist in data

Truck Route:
```
FID: 1340
Bylaw_Link: "http://www.bclaws.ca/civix/document/id/complete/statreg/30_78"
Provincial: 1
Designated: 1
Docu_PgNum: "N/A"
PDF_Page: "N/A"
City: "Vancouver"
RGN: "GVRD"
Restricted: 0
Type: "Provincial Highway"
TruckDefWt: null
Bylaw: "Commercial Transport Act, Div. 7"
AdviseType: "N/A"
Shape_Leng: null
AdviseDesc: "N/A"
SHAPE__Length: 30728.3572453521
```

Truck Advisories & Restrictions:
```
FID: 1367
Bylaw_Link: "https://westvancouver.ca/sites/default/files/bylaws/TrafficandParkingBylawNo.4370%2C2004.pdf#page=26"
Provincial: 0
Designated: 0
Docu_PgNum: "Pg. 23 - 24, 37 - 38"
PDF_Page: "Pg. 26 - 27, 40 - 41"
City: "West Vancouver"
RGN: "GVRD"
Restricted: 1
Type: "Truck Travel Restriction or Prohibition"
TruckDefWt: 10000
Bylaw: "No. 4370, 2004, Pt. 8.16"
AdviseType: "Restriction"
Shape_Leng: null
AdviseDesc: "Trucks, Trailers or Truck-Tractor combinations in excess of 10,000kg GVW are prohibited in a downhill direction. For this road, travelling southbound is prohibited"
SHAPE__Length: 1957.96330804532
```

Inspection Stations:
```
FID: 76
Scale: "Deas"
Open_Hours: "Random Operational Hours"
Street_Num: "PO Box 26006"
Address_St: "Richmond Post Office"
City: "Richmond"
Post_Code: "V6Y3V3"
Phone_Num: null
Fax_Number: null
Latitude: 49.129284
Longitude: -123.085385
Streetview: "https://www.google.ca/maps/@49.1295344,-123.0853661,3a,90y,218.76h,95.12t/data=!3m6!1e1!3m4!1sIXEY4Z_jxkRdowOZzqP3eQ!2e0!7i13312!8i6656"
```

Cardlock:
```
FID: 535
Cardlock: "7891 Grauer Road"
Alias: "Chevron - Richmond Cardlock"
Company: "Chevron"
Street_Num: 7891
Street_Nam: "Grauer Road"
City: "Richmond"
Latitude: 49.198184
Longitude: -123.136557
Streetview: "https://www.google.ca/maps/@49.1978368,-123.1370746,3a,60y,43.14h,82.4t/data=!3m6!1e1!3m4!1sxfUSX5XPVNHnkz8LY5fqkA!2e0!7i13312!8i6656"
Status: "Active"
```

Truck Parking:
```
FID: 176
Name: "Surrey Truck Park Inc."
Company: "Surrey Truck Park Inc."
Street_Num: 10607
Street_Nam: "Span Road"
City: "Surrey"
Phone_Numb: 6045885911
Latitude: 49.1954058
Longitude: -122.8892472
Streetview: "https://www.google.ca/maps/@49.1957862,-122.8887872,3a,80.2y,328.4h,94.51t/data=!3m6!1e1!3m4!1ssHaw3zWPmnnolZIfHX_M3A!2e0!7i13312!8i6656"
```

**Comment by al-tabb** [comment]
@qqnluaq Are you looking at the geodatabase or at the AGOL services?  I have added 'Notes' fields for datasets in the geodatabase.

**Comment by qqnluaq** [comment]
I don't have access to the GDB, only AGOL

**Comment by al-tabb** [comment]
I sent the GDB to you by email this morning.

**Comment by gk-tl** [comment]
Complete. Thank you.
