### ISSUE TITLE
Revise "Route Directions" Label

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#25]
Please consider changing the label for the "Route" button to "Get Route Details", “Get Directions”, or something similar. It is not immediately obvious that the user should click on "Route" to review/print turn-by-turn directions. 

Assuming this is where reports/notices will reside, "Get Route Details" rather than "Get Directions" would be more appropriate.

![Get Route](https://user-images.githubusercontent.com/59627982/72304801-866a6c00-3626-11ea-9b5a-5bf28231323f.png)

**Comment by qqnluaq** [comment]
revised button label, changed other buttons to icons to save space:

![image](https://user-images.githubusercontent.com/20274603/72765850-53ceef00-3ba3-11ea-8d7d-a522b59ef301.png)

**Comment by gk-tl** [comment]
Thank you. Complete.
