### ISSUE TITLE
Incorrect email in contacts list

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#256]
It has come to our attention that the email contact info for University Endowment Lands/UBC Area is incorrect in the Contacts.  The correct email for UBC is info.planning@ubc.ca

![image](https://user-images.githubusercontent.com/59742145/201231606-4d2a691c-b1e7-48e0-a1ad-fb7137bc39e2.png)

**Comment by NicoledeGreef** [comment]
@michaelpnelson  - i'll create a MAP ticket for this update in the contact info list and we can discuss and work it into a Sprint.

**Comment by michaelpnelson** [comment]
The contact email update has been deployed to all environments and confirmed in each:

develop: https://github.com/bcgov/smk-tlink/pull/258
qa: https://github.com/bcgov/smk-tlink/pull/257
production: https://github.com/bcgov/smk-tlink/pull/259
