### ISSUE TITLE
Generated Routes - Blue vs Red

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#26]
I noticed that in some cases the generated route (i.e., part of the route) is not colour coded correctly. Not sure if this has already been flagged elsewhere. Noting it just in case.

See example.

![Proposed vs Unverified Bug](https://user-images.githubusercontent.com/59627982/72305810-cc74ff00-3629-11ea-8c34-68c62e5bfe29.png)

**Comment by qqnluaq** [comment]
I don't see any problem in SMK, it's just rendering the data given to it by route planner. Forwarding to Refractions

**Comment by cmhodgson** [comment]
This is a known issue caused by the data being out of sync with current ITN. Once the data has been integrated into ITN these will be corrected. Graeme is working g on this now, with the hope that February's ITN will be able to have correct truck route flags in it.
