### ISSUE TITLE
Printing from iPhone issue

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#27]
iPhone 8 (iOS 13.3) printable route document has paging issue.  Page 1 content spills into page 2, page 3 into page 4, page 5, into page 6, etc.  A 5 page document on desktop becomes 11 pages on iPhone.

**Comment by NicoledeGreef** [comment]
issue fixed on iPhone 8 (iOS 13.3) .  there is a final blank page but that is probably reserved for notification text?

**Comment by gk-tl** [comment]
Tried print feature on iPhone 6 Plus. Not working. Please see screenhot of output:

![image](https://user-images.githubusercontent.com/59627982/72943003-c964c780-3d29-11ea-95f0-56d8410ed1ee.png)

**Comment by NicoledeGreef** [comment]
@gk-tl  - what iOS version is the iPhone Plus running? does anything happen if you select a Printer?

**Comment by gk-tl** [comment]
iOS 13.3. Notification message when trying to select a printer is "No AirPrint Printer Found", which is expected given our printers at the office don't support AirPrint.

**Comment by NicoledeGreef** [comment]
I am on iOS 13.3.1 and the app fails to launch the Printable document.  Once "Print" is clicked the apps indicates "Printing..." but the Print module in iOS doesn't materialize like it used to.

**Comment by NicoledeGreef** [comment]
hmmm just tried this again and it worked!

**Comment by gk-tl** [comment]
Pushing the print button brings up the following notification "Preparing print...", then nothing happens . I tried chrome and safari; the result was the same.


![Printing Screenshot](https://user-images.githubusercontent.com/59627982/73409344-d64a6380-42b3-11ea-9ff8-a8972dfd1878.jpg)

**Comment by NicoledeGreef** [comment]
@gk-tl i had the same issue on my iPhone again just now.  i restarted it, which i rarely do, and now the printable document generated as expected.  can you please try to replicate this on your phone?

**Comment by gk-tl** [comment]
Tried it on an iPhone 6 Plus S and iphone 7 Plus. Back to getting to this screen:

![image](https://user-images.githubusercontent.com/59627982/73876064-2755dc80-480b-11ea-9983-1d22601f7bd3.png)

Is this expected? Please note I cannot go any further than this given we don't have airprint enabled printers at our office.

**Comment by NicoledeGreef** [comment]
@gk-tl it is not expected.  it could be a symptom of no wireless printing.  is it possible for you try it somewhere that does have wireless printing?

**Comment by gk-tl** [comment]
I don't have an airprint enabled printer at home, so no way for me to check. If it works for you, then we're all good.

**Comment by gk-tl** [comment]
Thank you, Nicole.
