### ISSUE TITLE
Term Permit Routes layer

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#30]
Data provision is anticipated on January 24th.

@al-tabb to send us screen shots of desired symbolization (desired colour/symbol); as well it would be good to confirm the display name, where it should be placed in the layer list, draw order concerns.

**Comment by NicoledeGreef** [comment]
In addition to data, please provide:
Display Name,
Where the layer should appear in the layer list
Draw order
Desired colour/symbols

**Comment by al-tabb** [comment]
This layer will be completed this week and passed on to Nicole.
It is comprised of a line dataset and a point dataset.  The user should see this as one layer that it toggled on/off at the same time.
-Display name: Term Permit Route
-This layer should appear below OS/OW Routes in the layer list.
-This layer and Truck Routes / Truck Advisories & Restrictions should never be able to be visible at the same time.  If the user toggles on the Term Permit layer the Truck Route, Truck Advisories & Restrictions should toggle off and vice versa.
-This layer should have the same draw order as Truck Route/Truck Advisories & Restrictions (as they will never be visible at the same time)
Suggested Symbology:
![image](https://user-images.githubusercontent.com/59742145/73766532-028a3800-472b-11ea-930f-bf4d8e49e797.png)

**Comment by al-tabb** [comment]
@NicoledeGreef  Data sent by email.

**Comment by al-tabb** [comment]
@gk-tl  Feel free to weigh in  if you have different preferences for this layer.

**Comment by gk-tl** [comment]
- Overall Width (OAW) > 3.2 m Restricted —> rename to ”Overall Width (OAW) > 3.2 m Not Permitted”
- Overall Width (OAW) > 3.8 m Restricted —> rename to ”Overall Width (OAW) > 3.8 m Not Permitted“
- OS/OW Truck Restriction —> rename to “OS-OW Truck Restriction”
- TOL Roundabout —> rename to “Roundabout”

Please disregard the following sublayers:
- Time Restricted Non Truck Route
- Weight Restricted Non Truck Route
- Width Restricted Non Truck Route

None of these are eligible for through travel for staying standard trucks or OS-OW trucks under term permit.

Please combine:
- Height Restricted Truck Route - add to Potential Term Permit Route
 
Please rename the following:

Designated Truck Route —> ”Term Permit Route”. Add the following description to the comment/note field for this layer:

Municipal term permit limits: OAH 4.30 m, OAW 3.2 m, OAL 27.5 m, GVW 63,500 kg. Contact individual municipalities for details.

Provincial term permit limits: OAH 4.30 m, OAW 3.8 m, OAL - varies, GVW 64,000 kg. See BC Commercial Transport Procedures Manual for details.

Time Restricted Truck Route —> rename to “Time Restricted Term Permit Route”

Weight Restricted Truck Route —> rename to “Weight Restricted Term Permit Route”

Width Restricted Truck Route —> rename to “Width Restricted Term Permit Route”

Draw order:

Term Permit Route
Time Restricted Term Permit Route
Weight Restricted Term Permit Route
Width Restricted Term Permit Route

Overall Width (OAW) > 3.2 m Not Permitted
Overall Width (OAW) > 3.8 m Not Permitted
OS-OW Truck Restriction
Roundabout

Location - see card #29 

Please add a comment field to each of these layers/features

**Comment by gk-tl** [comment]
@NicoledeGreef and @qqnluaq - please hold off doing further work on this card and card #30. Alan is going to revise the data sets based on my comments and resubmit.

Over to you to @al-tabb

Thank you for bearing with me.

**Comment by gk-tl** [comment]
@al-tabb  here is the link to BC Commercial Transport Procedures Manual (Provincial term permit routes). 

https://www2.gov.bc.ca/gov/content/transportation/vehicle-safety-enforcement/information-education/commercial-transport-procedures

For municipal term permit routes, link to the "Contacts" page. 

This will be consistent with the description in the comment/note field.

> Term Permit Route”.
> Add the following description to a comment/note field for this layer:
> 
> * Municipal term permit limits: OAH 4.30 m, OAW 3.2 m, OAL 27.5 m, GVW 63,500 kg. Contact individual municipalities for details.
> * Provincial term permit limits: OAH 4.30 m, OAW 3.8 m, OAL - varies, GVW 64,000 kg. See BC Commercial Transport Procedures Manual for details.

**Comment by al-tabb** [comment]
@qqnluaq @NicoledeGreef Revised data has been sent by email.

**Comment by qqnluaq** [comment]
Suggestion: Instead of adding comments that revise earlier comments, just edit the original comment. The revisions are always available if needed.

I can see how to style `GM_TermPermit_Points`, based on the `Description` field. 

But I don't see enough information to style `GM_TermPermitRoutes`. I see 4 different classifications are required:
- Term Permit Route
- Time Restricted Term Permit Route
- Weight Restricted Term Permit Route
- Width Restricted Term Permit Route

But data in the layer only has a field named `TermPermitType` with 3 different values:
`"Restricted Term Permit Route"`, `"Restriction"` and `"Term Permit Route"`, and i see no other data that allows me to discriminate for time, weight, or width. `TermPermitRestriction` is an informational field, not something that can used for filtering.

**Comment by qqnluaq** [comment]
point features deployed, for approval

**Comment by al-tabb** [comment]
@qqnluaq Hi Ben, are we able to change the Roundabout Symbol to this?
![image](https://user-images.githubusercontent.com/59742145/75375390-c5751980-5882-11ea-846f-41b5377a1de0.png)

Also, just to note that I will be dropping all other Term Permit Point categories from the dataset in the next update.  The only thing that will remain will be the roundabouts.

**Comment by qqnluaq** [comment]
no problem

**Comment by al-tabb** [comment]
@qqnluaq For the Term Permit Linear features can we do the following?
'Term Permit Route' - dark green line (similar to Designated Truck Route)
'Restricted Term Permit Route' - light green line (similar to Designated Truck Route with Restriction)
'Restriction' - red line (similar to Restrictions in the Advisories & Restrictions layer.

**Comment by gk-tl** [comment]
Complete. Thank you.
