### ISSUE TITLE
Metadata links inventory

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#31]
Inventory the AGO Beta for the metadata links (Item description pages) as applicable.  The details in there will form the basis of the new metadata record stubs in the BCDC.

**Comment by NicoledeGreef** [comment]
In the AGO based beta (cvrp.translink.ca) I cannot find the links to metadata.  Often times the layer list contains hyperlinks to each layer's metadata record.

**Comment by NicoledeGreef** [comment]
Item pages in AGO have pertinent info that can be used for metadata records in the BCDC.  DataBC to transfer existing info to BCDC metadata records and then supply accounts to Translink for metadata editing and publishing.

**Comment by NicoledeGreef** [comment]
Inventorying the existing layers and metadata (in AGO) is underway.

**Comment by NicoledeGreef** [comment]
@gk-tl  and @al-tabb  - the list of layers and corresponding existing AGO item pages is attached.  please confirm my interpretation, especially the ones marked 'n/a' and 'n/a (net new)'. the list will be used by databc staff to create the new metadata record stubs.
[ago_service_urls.xlsx](https://github.com/bcgov/smk-tlink/files/4247532/ago_service_urls.xlsx)

**Comment by al-tabb** [comment]
@NicoledeGreef  I've made a few minor edits to the spreadsheet.
[ago_service_urls.xlsx](https://github.com/bcgov/smk-tlink/files/4295090/ago_service_urls.xlsx)

**Comment by NicoledeGreef** [comment]
thanks @al-tabb; 
re: Temporary Road Closures Extents - I see that data set in ArcGIS Online but it's not in the new map's layer list.   i am assuming that if the layer is not included in the new map then we need not create metadata for it in the BCDC but please let me know if you want to host the metadata/data for it in the BCDC.

**Comment by al-tabb** [comment]
Hi Nicole,  The Temporary Road Closures "layer" is actually made up of two datasets (point and polygon) although we would like it displayed in the legend as one layer for simplicity.  I think we should include both the point dataset and polygon dataset as well as their associated metadata in the BCDC.

**Comment by NicoledeGreef** [comment]
that explains it - thanks @al-tabb!
