### ISSUE TITLE
Routing between more than 2 waypoints

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#32]
The CVRP Beta Application (ArcGIS Online) allowed for 2 location inputs.  

The route planner web service can handle more than 2 easily, and that is the current implementation in TRP, but if we do leave it as more than 2 then we may have some user interface issues to attend to: the graphics for anything between start and finish points need work and on mobile there is not a lot of real estate to accommodate a long list of  locations.

**Comment by NicoledeGreef** [comment]
Desktop example of multiple waypoints:
![image](https://user-images.githubusercontent.com/26335003/72551945-b98d4500-384a-11ea-881e-a79222ce3381.png)

**Comment by qqnluaq** [comment]
FYI, the route planner allows re-ordering of waypoints. Just drag the handle to the left of the address in the list.

**Comment by NicoledeGreef** [comment]
Same example on mobile:
![image](https://user-images.githubusercontent.com/26335003/72554426-7e414500-384f-11ea-9787-236fb5126e89.png)

**Comment by NicoledeGreef** [comment]
Consider limiting to 4 in mobile the number of address a user can enter.  Action to check out how clicking works in terms of mobile.

On larger devices iPhone Plus, iPad Mini, and regular iPad can we have a higher limit?  What would be the effort?

**Comment by qqnluaq** [comment]
estimate for restricting to a max of N waypoints: 4 hours

**Comment by NicoledeGreef** [comment]
after discussing it with @gk-tl and @al-tabb, they mentioned preference for dropping waypoints on the map via click (or tap on mobile).  one can add as many waypoints as needed in this fashion on very limited mobile screen real estate. scrolling through the list is easy as is dragging the waypoints to different positions in the list.  

i think my bias was that i tend to enter addresses and exercise geocoder autocomplete feature.

all that said, @gk-tl - shall i close this ticket?  i do see a couple of minor UI items that i can create separate tickets for (address bar/waypoint conflict and blue markers don't match).

**Comment by gk-tl** [comment]
Thank you. Complete.
