### ISSUE TITLE
Legend Items Modification

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#33]
submitted by @al-tabb 

"Designated Municipal Truck Route with Restrictions" (light green) is currently labelled as "Designated Truck Route". This item should also be included in the "Truck Routes" legend item above it. This would eliminate the need to have a "Truck Routes" grouping.

Remove the "Truck Advisories and Restrictions" grouping and have "Restrictions & Warnings" and "Temporary Road Closures" outside of any grouping. Rename "Restrictions & Warnings" heading to "Truck Advisories and Restrictions".

**Comment by gk-tl** [comment]
Please note the order of legend entries from the TL BETA and adjust the TRP legend order / layer order accordingly.

![image](https://user-images.githubusercontent.com/59627982/73382414-4c32d880-427c-11ea-8c71-0cb6a28aae99.png)

1. Provincial Highway
2. Designated Municipal Truck Route
3. Designated Municipal Truck Route with Restrictions
4. Municipal Road with No Truck Restrictions
5. Federal Road with No Truck Restrictions

...etc...

**Comment by gk-tl** [comment]
Order of legend entries complete. Thank you.

Grouping in layer/legend widget remains to be addressed.

![image](https://user-images.githubusercontent.com/59627982/73473696-06404800-4342-11ea-8b9f-fbea9667adc2.png)

**Comment by gk-tl** [comment]
Type for Designated Municipal Truck Route **with Restrictions** ("with restrictions" missing for light green line). Also, should be placed under "Designated Municipal Truck Route"

![image](https://user-images.githubusercontent.com/59627982/73486720-8a062e80-435a-11ea-8d5f-16904a3fe029.png)

1. Provincial Highway
2. Designated Municipal Truck Route
3. Designated Municipal Truck Route with Restrictions

**Comment by gk-tl** [comment]
Complete. Thank you.
