### ISSUE TITLE
Legend / Route Planner 'Widget' Placement and Behaviour

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#34]
submitted by @al-tabb 

It may be helpful to have the legend and route planner 'widget' be independent from the other (Basemaps, feedback) functions of the app. I think they are the primary tools that the user will be interacting with so they should be open by default and should not be minimized/hidden while interacting with the other tools. Perhaps the legend could be on the other side of the screen and the Route Planner widget could be above the Basemaps/Feedback tools?

**Comment by NicoledeGreef** [comment]
@qqnluaq could you please estimate relative effort (hours) for this sort of enhancement?

**Comment by qqnluaq** [comment]
I propose a new widget that would be anchored in the bottom-right corner. It would expand and collapse (similar to the overview map), and show the current legend when expanded. It would duplicate the legend shown in the layers panel, as it would show legend entries for layers that actually visible. This legend panel's visibility would be independent of other panels.

It would probably not work well in a small screen (mobile) configuration.

I estimate 25 hours for this work.

**Comment by NicoledeGreef** [comment]
Speaking with @al-tabb and @gk-tl  they desire a standalone layerlist/legend as in the AGO beta.  Completely independent of the other widgets.

Routing and layerlist/legend independent of the others would be ideal.

**Comment by gk-tl** [comment]
Thank you for breaking out the legend as a separate widget. Works well in desktop environment, but takes up a lot of space on mobile devices (iPhone 6 Plus). It would be helpful to give the user the ability to minimize the legend to free screen space.

![file](https://user-images.githubusercontent.com/59627982/73379514-3d95f280-4277-11ea-8d70-837bdd04ba7c.jpeg)

**Comment by qqnluaq** [comment]
disabling legend in mobile view... until better solution is found

**Comment by gk-tl** [comment]
Thank you. Further to today's update call, I agree with the suggestion to leave the legend widget disabled in the mobile environment. However, it would be helpful if the legend could be turned on in the layers widget by default (for mobile devices).

Current default:
![image](https://user-images.githubusercontent.com/59627982/73485883-cd5f9d80-4358-11ea-881c-0edb22c59c3f.png)

Proposed:
![image](https://user-images.githubusercontent.com/59627982/73485961-f6802e00-4358-11ea-8d99-a2eb602decbb.png)

**Comment by gk-tl** [comment]
Complete. Thank you.
