### ISSUE TITLE
Ability to drag waypoints on the map

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#38]
Drag and drop of point on the map?

Rationale: can help with large sites that have multiple access points (user can adjust it as needed).  

Example: Krause Berry Farms delivery access point versus visitor access point

@qqnluaq  Effort to implement?

**Comment by qqnluaq** [comment]
estimate 2 days to implement draggable waypoints

**Comment by gk-tl** [comment]
Complete. Thank you.
