### ISSUE TITLE
Ability to drag route on the map

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#39]
After entering an address or clicking a to establish waypoints and a route can a user drag a route (similar to Google Maps)?

Note: Drag the waypoint is higher priority than drag the route.

**Comment by NicoledeGreef** [comment]
@qqnluaq - estimate of effort to develop?

**Comment by qqnluaq** [comment]
estimate 2 days to implement draggable wayponts

**Comment by qqnluaq** [comment]
If draggable waypoints are implemented then I think this task reduces to being able to add a waypoint in middle of existing route. 
Estimate 3 days

**Comment by NicoledeGreef** [comment]
Moved to Icebox; not for March 31 based on discussion with @gk-tl and @al-tabb on Jan 24

**Comment by mraross** [comment]
I agree with Ben. Adding and moving waypoints is all you need.
