### ISSUE TITLE
Add definition of Potential & Unverified Route

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#40]
**Please add the definitions copied below, as follows.**

1. Please include a legend entry with a name for each route type (“Potential Route” and “Unverified Route” – as currently provided in the TL BETA, noting the change to “Potential Route” instead of “Proposed Route”).

2. When a route is generated, please Include the two definitions in the report/notice and the printed route itinerary (either at the top or bottom of the printout).

3. It should also be relatively straight forward to create a static glossary page where we can include term definitions like these.

**Generated Route Type Definitions, as reviewed and revised by TL Legal:**

Change “Proposed Route” to “Potential Route”

**Potential Route (Blue Line)** – A route that based on factors such as the origin and destination, intermediate waypoints, and the default or user-entered vehicle parameters, may comply with municipal truck route bylaws. This route is put forward for the driver and/or carrier’s consideration for pre-trip planning purposes without warranty of any kind, whether express or implied. The driver and/or carrier is responsible for ensuring the default vehicle parameters or user-entered vehicle parameters are an accurate representation of the actual vehicle, for verifying all clearances and restrictions on the route, and for ensuring the vehicle is operated in compliance with all applicable municipal bylaws and provincial and federal regulations.

**Unverified Route (Dotted Red Line)** – A route, or a portion of a route, that may not comply with municipal truck route bylaws and may not be suitable for a vehicle with the default or user-entered vehicle parameters. The driver and/or carrier is responsible for ensuring the default vehicle parameters or user-entered vehicle parameters are an accurate representation of the actual vehicle, for verifying all clearances and restrictions on the route, and for ensuring the vehicle is operated in compliance with all applicable municipal bylaws and provincial and federal regulations. 

Related tickets: #15, #21

**Comment by gk-tl** [comment]
Part 1 is complete. Thank you.

> Please include a legend entry with a name for each route type (“Potential Route” and “Unverified Route” – as currently provided in the TL BETA, noting the change to “Potential Route” instead of “Proposed Route”).

I might have missed something, but Part 2 and 3 seem to be a work in progress. Should I split them out into separate tickets?

**Comment by qqnluaq** [comment]
yes, sorry. parts 2 & 3 are still in progress.

**Comment by gk-tl** [comment]
No need to apologize. Thank you.

**Comment by gk-tl** [comment]
Complete. Glossary page is also addressed in another ticket - #41 . Closing this ticket. Thank you.
