### ISSUE TITLE
Add the Province to Disclaimer

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#42]
TL legal suggestion - the Province should probably be added as a named entity in the disclaimer.

[2020-01-09 CVRP Disclaimer Text.docx](https://github.com/bcgov/smk-tlink/files/4088526/2020-01-09.CVRP.Disclaimer.Text.docx)

**Comment by NicoledeGreef** [comment]
Alex R. is going to follow up on this item.

**Comment by AlexanderRitchie** [comment]
Have meeting with Legal on topic Monday Feb 3rd.

**Comment by AlexanderRitchie** [comment]
@NicoledeGreef 

please proceed with:
“Under no circumstances will Translink or any of its partners or stakeholders (including, without limitation, the Province of BC) be liable….. even if Translink or any of its partners or stakeholders (including, without limitation, the Province of BC) has have been specifically advised."

There may be additional update after a meeting later this week at which time I will advise if needed.

Thanks,

-Alex

**Comment by qqnluaq** [comment]
This is the current text:

> Under no circumstances will TransLink be liable to any person or business entity for any direct, indirect, special, incidental, consequential, or other damage based on any use of this website or any other website to which this site is linked, including, without limitation, any lost profits, business interruption, or loss of programs or information, even if TransLink has been specifically advised.

@AlexanderRitchie  please reply with new version.

**Comment by gk-tl** [comment]
Here is what I sent to TL legal for review (revised text in **bold**)

This website (the Truck Route Planner (TRP) Beta) and all of the information it contains are provided "as is" without warranty of any kind, whether express or implied. All implied warranties, including, without limitation, implied warranties of merchantability, fitness for a particular purpose, and non-infringement, are hereby expressly disclaimed.

Links and references to any other websites are provided for information only and listing shall not be taken as endorsement of any kind. TransLink **or any of its partners or stakeholders (including, without limitation, the Province of BC)** are not responsible for the content or reliability of the linked websites and does not endorse the content, products, services or views expressed within them.

Under no circumstances will TransLink **or any of its partners or stakeholders (including, without limitation, the Province of BC)** be liable to any person or business entity for any direct, indirect, special, incidental, consequential, or other damage based on any use of this website or any other website to which this site is linked, including, without limitation, any lost profits, business interruption, or loss of programs or information, even if TransLink **or any of its partners or stakeholders (including, without limitation, the Province of BC)** has been specifically advised.
 
This website is intended to be used as a pre-trip planner. Do not operate a vehicle while using this website.

By proceeding, you are accepting this disclaimer, and you are indicating you understand the limitations of this website.

I accept the disclaimer and understand the limitations of this website

**Comment by qqnluaq** [comment]
Great thanks

**Comment by NicoledeGreef** [comment]
please see alex' comment above from 4 days ago.  he was hoping to have the paragraph appended to the existing disclaimer.

**Comment by AlexanderRitchie** [comment]
Confirmed updates from @gk-tl are correct.
Thanks.

**Comment by gk-tl** [comment]
Please note correction to a typo:

Under no circumstances will TransLink or any of its partners or stakeholders (including, without limitation, the Province of BC) be liable to any person or business entity for any direct, indirect, special, incidental, consequential, or other damage based on any use of this website or any other website to which this site is linked, including, without limitation, any lost profits, business interruption, or loss of programs or information, even if TransLink or any of its partners or stakeholders (including, without limitation, the Province of BC) **_have_** been specifically advised.

**Comment by gk-tl** [comment]
Complete. Thank you.

Heads-up (not actionable at this time): I anticipate submitting a new ticket (likely next week) after we confirm adding a new paragraph to the disclaimer (as suggested by Alex), which is currently under legal review.

---NEW PARAGRAPH---

**TransLink and the Province of BC, in their sole discretion, may at any time without notice revise the content and features of this website and the terms and conditions of its use, or terminate this website at any time, for any reason, without any notice and without any liability to any person or business entity.**

---END NEW PARAGRAPH---

**Comment by NicoledeGreef** [comment]
noted - thanks!
