### ISSUE TITLE
Update Restriction; Advisory; Application; Border Crossing Messages

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#43]
Please update the text for the various message types. EXCEL file includes the original TL BETA text and proposed revisions.
[2020-01-21 RestrictionAdvisoryApplicationMessages.xlsx](https://github.com/bcgov/smk-tlink/files/4092650/2020-01-21.RestrictionAdvisoryApplicationMessages.xlsx)

**Comment by gk-tl** [comment]
Please add the following report/notice message when user inputs an O/D at a marine terminal in Metro Vancouver (South Shore Terminals, North Shore Terminals, Delta Port, Fraser Surrey Docks)

"This route includes a Port Restricted Access road. All container trucks accessing port container terminals must hold a valid Truck License System (TLS) licence. The TLS program requires all drayage companies and trucks draying marine containers to or from the port to enter into an Access Agreement from the port authority prior to accessing port facilities. This applies to all parties draying, both local and long haul. Follow the link for more information about the TLS and ports access requirements: https://www.portvancouver.com/truck-rail/truck"

**Comment by NicoledeGreef** [comment]
Replacement completed:
![image](https://user-images.githubusercontent.com/26335003/73795704-1ef49780-4760-11ea-91c5-d195078f34d5.png)

Turning over the updated file to @qqnluaq in a new ticket so closing this one.
