### ISSUE TITLE
Editing Waypoints

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#45]
What would be the level of effort to allow a user to edit way points, including the starting point? Preference would be to give the user the ability to edit way points by dragging and dropping or by address search.

![image](https://user-images.githubusercontent.com/59627982/72949250-9d9f0d00-3d3c-11ea-9c46-6adf558fe324.png)

**Comment by NicoledeGreef** [comment]
Dragging waypoints ticket: https://github.com/bcgov/smk-tlink/issues/38

**Comment by qqnluaq** [comment]
Dragging the waypoints doesn't look too difficult, say 2 days.

Changing a waypoint by entering a new address seems difficult. However it is possible to add a new  waypoint at this address. Then one can delete any waypoints not need, and re-order the remaining waypoints to construct wanted route.

**Comment by gk-tl** [comment]
Thank you for the estimate. It seems reasonable to focus on the ability to edit way points by dragging them. No need for pursuing editing waypoints by entering a new address..
