### ISSUE TITLE
Use coordinates, not reverse geocode when interpreting user clicks on the map

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#46]
@mraross suggested that instead of resolving clicks on the map to addresses, we should resolve then to coordinates because  when users drop a point on the map it'sbecause they want to reach that specific point, not the nearest address.  See an example of this in https://office.refractions.net/~chodgson/gc/ols-demo/?rt=rri though this app has 2 clicks probably not necessary for truckers but good for QA purposes in the LSIA app.

![image](https://user-images.githubusercontent.com/26335003/73014321-ce2f8700-3dce-11ea-8a87-39b28fcd8617.png)

**Comment by NicoledeGreef** [comment]
@qqnluaq  - please supply an estimate for this enhancement.

**Comment by qqnluaq** [comment]
Would it make sense to show the address if it is available for the point clicked on?
EG:
49.2345, -123.3245 (123 Fake st, comox,BC)

Either way its about 1 day of effort.

**Comment by gk-tl** [comment]
Resolving to the coordinates makes sense. Showing the closet address as Ben suggests is good.

**Comment by gk-tl** [comment]
Complete. Thank you.

**Comment by gk-tl** [comment]
Previously suggested/implemented feature to allow clicks on the map to resolve to coordinates does not appear to be working. For example, user cannot specify way points for marine terminals on the south shore - clicking on the truck gate at Centerm terminal snaps to 711 Alexander Street.

![image](https://user-images.githubusercontent.com/59627982/76657802-eb134b80-652f-11ea-9782-a7414f42f884.png)

**Comment by qqnluaq** [comment]
modified behaviour: the exact location clicked on is always used as the waypoint location, and best effort is made to find an address for point.

**Comment by gk-tl** [comment]
Great. Thank you, Ben.

Complete.
