### ISSUE TITLE
Province of BC logo to be included alongside TransLink

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#47]

**Comment by NicoledeGreef** [comment]
Alex R. to confirm.

**Comment by AlexanderRitchie** [comment]
Currently exploring topic with appropriate resources.

**Comment by NicoledeGreef** [comment]
This need was confirmed by today.  

@AlexanderRitchie  - shall we place the attached provincial logo (attached) to the left of the Translink logo wherever it occurs, i.e. on the Disclaimer, banner, on the printable report and possibly elsewhere?
[gov_bc_logo.zip](https://github.com/bcgov/smk-tlink/files/4726596/gov_bc_logo.zip)

**Comment by AlexanderRitchie** [comment]
> This need was confirmed today.
> 
> @AlexanderRitchie - shall we place the attached provincial logo (attached) to the left of the Translink logo wherever it occurs, i.e. on the Disclaimer, banner, on the printable report and possibly elsewhere?
> [gov_bc_logo.zip](https://github.com/bcgov/smk-tlink/files/4726596/gov_bc_logo.zip)

@NicoledeGreef  - yes please. Request was for in the main banner, but good strategy to put logo to the left of all existing TransLink logos.

Thanks!

**Comment by NicoledeGreef** [comment]
@qqnluaq  - this was in the Icebox for a while but has now been approved through the necessary channels.

**Comment by NicoledeGreef** [comment]
Reviewing in https://translink-d.apps.gov.bc.ca/trp/ using Chrome, it seems the Translink logo has disappeared (either replaced or obscured by the other logo on the banner.
![image](https://user-images.githubusercontent.com/26335003/83905313-4cede680-a716-11ea-9c4e-181b7443e4ce.png)

Also, in the printable report, it looks like a different format logo would be better.
![image](https://user-images.githubusercontent.com/26335003/83905137-04362d80-a716-11ea-9db8-23ec0421b430.png)

**Comment by qqnluaq** [comment]
hmm, somewhat contrary to what I see! investigating...

**Comment by qqnluaq** [comment]
Is there another version of the bc logo suitable for white background?

**Comment by NicoledeGreef** [comment]
This ZIP file contains *all the files:

https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/policies-procedures-standards/web-content-development-guides/corporate-identity-assets/visid-files/2018_bcmark_files.zip?forcedownload=true

Once you extract, try ..\2018_bcmark_files\2018_BCID_Files\_Horizontal\Positive\RGB\BCID_H_rgb_pos.png

**Comment by NicoledeGreef** [comment]
Reviewed  https://translink-d.apps.gov.bc.ca/trp/ using Chrome, Firefox, and Edge on Windows and in Safari on iPhone 8.  Chrome and FireFox and Safari show both logos in the Disclaimer banner, app banner and on the printable PDF.

Oddly MS Edge shows the logos on the banners but is not showing the Translink logo on the printable PDF however:
![image](https://user-images.githubusercontent.com/26335003/83925477-1dea6b80-a73c-11ea-96b8-6b901a0358f8.png)

**Comment by qqnluaq** [comment]
should be OK now

**Comment by NicoledeGreef** [comment]
Verified that the printable PDF in Edge contains both logos - thanks @qqnluaq !

**Comment by gk-tl** [comment]
Complete. Thank you.
