### ISSUE TITLE
TRP: remove truck route multiplier parameter

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#49]
In the TransLink app, the truck route multiplier is set at such a level that causes unnecessarily long routes. Al at TransLink suggests that it be changed to a value just greater than 13 so try 15.

**Comment by NicoledeGreef** [comment]
@mraross:
Maybe set the truck route multiplier to 13 for now. Setting it higher with turn-costs on causes unnecessary travel but that could be due to a bug in turn-costs. See https://github.com/bcgov/ols-router/issues/202

**Comment by qqnluaq** [comment]
Just so we're clear, the default value for the multiplier is 10 at the moment. Do you want me to increase it to 15?

**Comment by NicoledeGreef** [comment]
I don't think that was the intent.  @mraross?

**Comment by mraross** [comment]
Yes, that was Al's suggestion.

**Comment by NicoledeGreef** [comment]
As per @mraross , what we now need to do is to remove the truckMultiplier parameter altogether.  The route planner is going to default to what is needed by the TRP.

**Comment by gk-tl** [comment]
Complete. Thank you.
