### ISSUE TITLE
Use of Default Location

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#50]
Option: Don't provide a default location
-->Good for dispatch and truckers

Option: Give users a choice to use their location; see maps.google.ca on a phone for an example (small crosshairs bull's eye icon on the map)
-->Good for truckers

**Comment by NicoledeGreef** [comment]
@qqnluaq  - please provide estimate for implementing each Option.

**Comment by qqnluaq** [comment]
I could add a button to the route planner UI that would add the current location as a waypoint.
So, the route planner would start up with no waypoints. The user can either click on the map somewhere, enter an address or click button to add current location.

1 day of effort

**Comment by gk-tl** [comment]
Complete. Thank you.
