### ISSUE TITLE
Display of Reports & Notices

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#53]
Reports & Notices should be displayed in a modal window that is invoked with the click on a button (widget icon). See example from previous CVRP Beta release.
![image](https://user-images.githubusercontent.com/26335003/73678118-85988900-466c-11ea-952b-f054df617992.png)

![image](https://user-images.githubusercontent.com/26335003/73678196-b7115480-466c-11ea-8821-1d988e635100.png)

**Comment by NicoledeGreef** [comment]
once route generated, if applicable, highlight the fact that there are notifications to be considered.  change icon colour to red in that instance.

**Comment by gk-tl** [comment]
Complete. Thank you.
