### ISSUE TITLE
Truck Definition by Municipality integration

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#57]
truckdefbymunicipality is a table that defines the concept of what is a truck in a given municipality.

TRP needs to use it to x-ref routing search parameters (truck options) and municipalities in order to generate Application Message:

"Based on the GVW and axle count, your vehicle is not considered to be a heavy truck in the following municipalities: [LIST of applicable municipalities]. The driver and/or carrier is responsible for ensuring the default vehicle parameters or user-entered vehicle parameters are an accurate representation of the actual vehicle, for verifying all clearances and restrictions on the route, and for ensuring the vehicle is operated in compliance with all applicable municipal bylaws and provincial and federal regulations. [LINK to Municipal and Provincial contact information]"

**Comment by NicoledeGreef** [comment]
@al-tabb - please provide the table via email to @qqnluaq and CC @NicoledeGreef , or attach to the ticket.

**Comment by al-tabb** [comment]
Table sent via email.

**Comment by qqnluaq** [comment]
Can I get the actual [LINK to Municipal and Provincial contact information] ?

**Comment by qqnluaq** [comment]
Also, in the table, the entry for municipality '*' is the catch-all for any muni that doesn't appear in table?

**Comment by qqnluaq** [comment]
I just noticed that the Application Message mentions the axle count, but the table of municipalities only includes the GVW.

If the route passes through localities not mentioned in this table, is the expectation that the '*' GVW applies, and the locality name should be included in the list of names in Application Message?

**Comment by NicoledeGreef** [comment]
@al-tabb and @gk-tl  please see questions above re: data.

**Comment by gk-tl** [comment]
> Can I get the actual [LINK to Municipal and Provincial contact information] ?

We need a new contacts page as per ticket #36 

Content: https://cvrp.translink.ca/contacts

**Comment by al-tabb** [comment]
> If the route passes through localities not mentioned in this table, is the expectation that the '*' GVW applies, and the locality name should be included in the list of names in Application Message?

Yes, I believe that is correct.

**Comment by al-tabb** [comment]
> I just noticed that the Application Message mentions the axle count, but the table of municipalities only includes the GVW.

Yes, I suppose the message is more general than the way the logic in the application works.  Currently we only use the GVW when determining if a vehicle qualifies as a truck in specific municipalities.  @gk-tl I suppose we could change this message to remove the mention of axle count if you wish.  The only time axle count comes into play is to determine if a vehicle is a permit vehicle.  It does not affect routing but does trigger a fully unverified route (dotted red line).

**Comment by gk-tl** [comment]
@al-tabb No need to modify the app message.

**Comment by gk-tl** [comment]
I believe this ticket is complete. Question re. contacts is addressed in ticket #36.
