### ISSUE TITLE
Handling of route exceptions (edge cases)

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#59]
Regarding Card #210 (https://github.com/bcgov/ols-router/issues/210#issuecomment-578331823), it would be helpful to discuss how the TRP is going to handle route exceptions (edge cases) such as Front Street vs Royal Ave (New West), Haney Bypass vs Lougheed (Maple Ridge), Port access via Commissioner Street vs Clark Drive (Vancouver).

--- Excerpt from Card #210 ---

> All of the exceptions are captured in the table ‘exceptions’ in the PostGIS database. There is a python script that I believe I passed on earlier that calculates the ‘default cost’ of all segments based on their truck route status and road type. The ‘final costs’ of any exception segments are calculated from the information captured in the ‘exceptions’ table.

> During a follow-up conversation re. this ticket, @al-tabb aptly pointed out exceptions are needed given there will always be edge cases where we need to calculate costs differently from our general classification scheme (i.e. opening up a small number of private, restricted, etc. roads for truck travel).

> An exceptions table would address the Royal Ave vs Front Street route and any other "fine tuning" needed to generate routes consistent with user expectations that don't fit the general classification scheme.

Suggest @al-tabb and @mraross discuss this further.

**Comment by mraross** [comment]
Agreed. That's what our meeting is about tomorrow. Our proposal is a refinement of Al's approach and is captured here:

 https://github.com/bcgov/ols-router/issues/215

**Comment by gk-tl** [comment]
@mraross Thank you, Michael.

**Comment by NicoledeGreef** [comment]
Given this is specific to the router I will close this ticket for now.

**Comment by mraross** [comment]
Sure
