### ISSUE TITLE
Update Truck Advisories & Restrictions data

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#67]
I have provided a new Truck Advisories & Restrictions dataset 'GM_TruckRoutes' by email.  There are a couple of small changes (bridge restrictions).

**Comment by gk-tl** [comment]
Restriction/advisory description is missing for “Designated Truck Route with Restrictions” layer.

**Comment by gk-tl** [comment]
Example from TL BETA - 108TH Ave in Surrey

![image](https://user-images.githubusercontent.com/59627982/74961109-62870c80-53c2-11ea-9f1d-9e738fc130af.png)

@al-tabb indicated this could be a result of recent updates he made to the field names.

**Comment by gk-tl** [comment]
Complete. Thank you. 

Created new ticket (#74) regarding missing restriction/advisory description.
