### ISSUE TITLE
Configure metadata links in app

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#68]
Once #31 and #65 are complete, the BCDC metadata permalinks can be incorporated into the TRP app.

**Comment by NicoledeGreef** [comment]
Here are the permalinks for the draft BCDC records.  Please configure them into the app, @qqnluaq 

Translink - Metro Vancouver Boundary
https://catalogue.data.gov.bc.ca/dataset/874721e7-6d61-49f4-8bd0-379904575d2b

Translink - Provincial Highway
https://catalogue.data.gov.bc.ca/dataset/44f64352-7baf-478f-8437-ba97157b142f

Translink - Downtown Vancouver
https://catalogue.data.gov.bc.ca/dataset/e919fa95-b8e2-4d98-9354-055fe8ecb1a7

Translink - Industrial Areas
https://catalogue.data.gov.bc.ca/dataset/5e590c8e-af1b-4217-b84b-ee6f3cbc911f

Translink - Port of Vancouver Facilities / Terminals
https://catalogue.data.gov.bc.ca/dataset/67e381f5-0ee3-437b-ba55-15789842f4db

Translink - Truck Parking
https://catalogue.data.gov.bc.ca/dataset/32e62210-713d-4dcd-8b33-9591d6044cd3

Translink - Cardlocks
https://catalogue.data.gov.bc.ca/dataset/66398912-7103-4557-a17e-6a5d68577fba

Translink - Inspection Stations
https://catalogue.data.gov.bc.ca/dataset/b0e1d7f5-a9aa-4c9b-a3d4-6ee36f3027cf

Translink - Height Restrictions
https://catalogue.data.gov.bc.ca/dataset/f3c942c0-7188-4661-82c8-1c46a82f7520

Translink - Oversize-Overweight (OS-OW) Truck Routes
https://catalogue.data.gov.bc.ca/dataset/4798ee98-f87d-400b-9926-704ba96ef6ab

Translink - Dangerous Goods Eligible Route
https://catalogue.data.gov.bc.ca/dataset/9e5c73cf-b0cc-4ed7-b703-1b15e3489712

Translink - Temporary Road Closures
https://catalogue.data.gov.bc.ca/dataset/57a545b3-8520-4fe2-a718-21d9a6fd65f6

Translink - Truck Routes
https://catalogue.data.gov.bc.ca/dataset/0636a01a-a13f-48f9-94cf-1c0e59b3ba6b

**Comment by qqnluaq** [comment]
At present SMK doesn't display these metadata links anywhere in the app. Where would you expect to see them?

**Comment by gk-tl** [comment]
How about in the Glossary?

**Comment by NicoledeGreef** [comment]
They are now hyperlinked from the layer name, which is typical of mapping applications.

**Comment by gk-tl** [comment]
Sounds good. Thank you.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - slight change for the time being.  please update Provincial Highway to point to the Truck Routes metadata record as it is part of the same dataset:
https://catalogue.data.gov.bc.ca/dataset/0636a01a-a13f-48f9-94cf-1c0e59b3ba6b

The Provincial Highway record is becoming a placeholder record for Term Permits (future use).

**Comment by gk-tl** [comment]
Complete. Thank you.
