### ISSUE TITLE
Add following text to "Note" field for the "Term Permit Route" Layer

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#69]
@al-tabb - please add following text to the note field for term permit routes

**THIS IS AN INTERIM MAP LAYER AND SHOULD ONLY BE USED AS AN AID FOR PRE-TRIP PLANNING.**

Please contact the Provincial Permit Centre and individual municipalities to confirm that the routes and related information in this map layer are consistent with municipal, provincial, and federal requirements established in applicable Acts, regulations, bylaws, policies, and procedures respecting the transport of oversize-overweight vehicles and/or loads. 

In the event of a discrepancy between this map layer and municipal, provincial, and federal requirements, the municipal, provincial, and federal requirements apply and override the information in this map layer. 

The driver and/or carrier is responsible for for verifying all clearances and restrictions on a proposed route and for ensuring the vehicle is operated in compliance with all applicable municipal, provincial, and federal requirements.

**Comment by qqnluaq** [comment]
Is this to be done for the line or point features or both?
I haven't added the line features to map yet, btw: see #30

**Comment by gk-tl** [comment]
This will only apply to the line features. 

Upon review of the point features with @al-tabb , please disregard them entirely (except the roundabouts). The information is redundant given the line features already have all of the same info.

@al-tabb is updating the data.

**Comment by al-tabb** [comment]
@qqnluaq In order to preserve the paragraphs that @gk-tl has specified am I able to put in html tags (i.e. <p></p>)?

**Comment by qqnluaq** [comment]
yes

**Comment by qqnluaq** [comment]
@al-tabb @gk-tl There's still an issue with the term permit route line features, see #30

**Comment by al-tabb** [comment]
Complete.
