### ISSUE TITLE
Blocker: Disclaimer on iOS devices

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#7]
Version: 0.8.1
Last commit: 2019-12-18 14:33:42 -0800

When viewed in Safari on iOS 13.3 (iPhone 8) and iOS 9.3.5 (ipad mini), there appears to be a disabled text box beneath the "I accept" button.

Also, if you tap the "I accept..." button, the disclaimer panel does not disappear as when viewed in desktop mode.  Rather it takes user to the top of the Disclaimer form.

**Comment by NicoledeGreef** [comment]
it would be ideal to fix this ASAP; BC Trucking Association is set to  publish a call out to their members in their January 6 bulletin to invite participation in the test group.

**Comment by qqnluaq** [comment]
I just pushed a build fixing this issue

**Comment by NicoledeGreef** [comment]
thanks @qqnluaq  - I'll review now.

**Comment by NicoledeGreef** [comment]
Beta ver: 0.0.2 built: 2019-12-20

Fix verification

-works much better now on iPhone 8 running iOS 13.3

-site will not load on iPad mini running  iOS 9.3.5 - white screen - not too concerned about this given the age of the version and device.
