### ISSUE TITLE
Set up github-->Openshift pipelines for PROD and non-PROD hosting environment

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#72]
We have the OpenShift Project available to us now.  This task is to set up the  PROD and non-PROD containers and establish the pipelines from GitHub to Openshift.

**Comment by NicoledeGreef** [comment]
relates to: https://proj.data.gov.bc.ca/jira/browse/LOC-892

**Comment by dkelsey** [comment]
I was working on getting webhooks working.  They don’t work at this point.
The may be related to a routing issue in the environment.
For now I can get the apps updated by re-starting them.
 
* The dev version of the site will update to what is in the develop branch of the code repo.
* The test version will update for what is in the test branch
* And the prod version will do the same for the master branch.

**Comment by NicoledeGreef** [comment]
thanks @dkelsey
