### ISSUE TITLE
Add On/Off Ramps for GEB to TRN in TOL

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#73]
@al-tabb please add the on-off ramps for the Golden Ears Bridge (GEB) in the Township of Langley (TOL) to the truck route network (TRN). 

Same  designation/symbols as the GEB ("Designated Municipal Truck Route with Restrictions")

![GEB on-off Ramps TOL](https://user-images.githubusercontent.com/59627982/75281772-b3cd3c80-57c4-11ea-8115-8376dc3f2d28.png)

**Comment by al-tabb** [comment]
Complete.
