### ISSUE TITLE
Issues specific to Legacy Edge

### ISSUE THREAD

**Issue by qqnluaq** [bcgov/smk-tlink#77]
After testing in Edge (Legacy), add any issues to this ticket. Update this description as needed.

- [x] in route planner, clicking on map may not insert a waypoint
- [x] in route planner, route calculation always fails, and leaves UI in inconsistent state
- [x] anywhere in UI, a SHIFT-click will select all text (layers)
- [x] font for waypoint descriptions is serif for some reason
- [x] layers panel has legend toggle on new line

**Comment by gk-tl** [comment]
Complete. Thank you.
