### ISSUE TITLE
Broken link in Reports & Notices

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#78]
"LINK to Municipal and Provincial contact information"
is a broken link.

Version 0.0.16
invoked if I route through Richmond with default truck settings

**Comment by NicoledeGreef** [comment]
Might be a data issue.  @qqnluaq  - can you please investigate and confirm?  if data, please re-assign to Al.

**Comment by qqnluaq** [comment]
There was no link provided with #57

**Comment by NicoledeGreef** [comment]
@al-tabb - any insight you have on this is appreciated.

**Comment by al-tabb** [comment]
Where does the broken link show up?  In one of the cartographic datasets or in the notifications/report?

**Comment by NicoledeGreef** [comment]
notifications is where i believe i saw it.  cannot reproduce at the moment as the route planner is offline for data reconciliation activities

**Comment by qqnluaq** [comment]
One way to get it is make the route traverse Richmond

**Comment by al-tabb** [comment]
This should link to the ;Contacts' page which has yet to be created.  Once we know the hyperlink we'll have to pass it on to @gleeming to update the routing dataset.

**Comment by NicoledeGreef** [comment]
relates to #88

**Comment by gk-tl** [comment]
Complete. Thank you.
