### ISSUE TITLE
Please add "Dangerous Goods Restrictions"

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#85]
@al-tabb is going to provide a point data set for two dangerous goods restrictions established in Provincial Regulations - George Massey Tunnel and Cassiar Connector Tunnel. 

**Name:** 
"Dangerous Goods Restrictions"

**Draw order/Placement:**
Same position as "Dangerous Goods Eligible Routes" (i.e., in lieu of this layer)

**Icon/Symbol:**
![DG-HM Prohibition R-126](https://user-images.githubusercontent.com/59627982/76472813-dc078e80-63b3-11ea-9693-9242bed1ea4f.png)

Related to card #84

**Comment by al-tabb** [comment]
Data set has been provided by email.

**Comment by gk-tl** [comment]
Complete. Thank you.
