### ISSUE TITLE
Truck parameters reset when accessed multiple times

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#86]
If the user changes the truck parameters, moves out of the vehicle configurations (changes to identify, layer list, etc.) then moves back into the truck parameters the values are reset to the default.  I think it would be better if the changed parameters were remembered.  This allows the user to make incremental changes to their vehicle type.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - estimate please.

**Comment by qqnluaq** [comment]
estimate 4h

**Comment by gk-tl** [comment]
Complete. Thank you.
