### ISSUE TITLE
Unable to print route itinerary

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#87]
I'm currently unable to print my route itinerary.  I am using Chrome.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - verified issue on march 2 @3:25pm

console output:
smk.js:153 layer id "temporary-road-closure-extent" isn't defined
get @ smk.js:153
2smk.js:153 layer id "temporary-road-closure" isn't defined
get @ smk.js:153
3smk.js:153 layer id "temporary-road-closure-extent" isn't defined
get @ smk.js:153
3smk.js:153 layer id "temporary-road-closure" isn't defined
get @ smk.js:153
smk.js:2 included template "report.report-not-heavy-truck-html" ./fragments/report-not-heavy-truck.html
smk.js:2 included template "report.report-direction-notification-html" ./fragments/report-direction-notification.html
2smk.js:495 TypeError: Cannot read property 'features' of undefined
    at (index):298
    at i.handleRouteData (smk.js:495)
    at smk.js:495
    at async Promise.all (/smk-tlink/index 1)
(anonymous) @ smk.js:495
smk.js:1274 [Vue warn]: Error in event handler for "directions-route.print": "TypeError: Cannot read property 'class' of undefined"

(found in <Root>)
ce @ smk.js:1274
smk.js:1274 TypeError: Cannot read property 'class' of undefined
    at smk.js:332
    at Array.forEach (<anonymous>)
    at e.getConfig (smk.js:332)
    at Un.print (smk.js:480)
    at Un.Mn.$emit (smk.js:1274)
    at e.emit (smk.js:332)
    at Un.trigger (smk.js:324)
    at Un.e [as trigger] (smk.js:1274)
    at o.$$emit (smk.js:1299)
    at Proxy.e (smk.js:1274)
Qe @ smk.js:1274
smk.js:1274 [Vue warn]: Error in event handler for "directions-route.print": "TypeError: Cannot read property 'class' of undefined"

(found in <Root>)
ce @ smk.js:1274
smk.js:1274 TypeError: Cannot read property 'class' of undefined
    at smk.js:332
    at Array.forEach (<anonymous>)
    at e.getConfig (smk.js:332)
    at Un.print (smk.js:480)
    at Un.Mn.$emit (smk.js:1274)
    at e.emit (smk.js:332)
    at Un.trigger (smk.js:324)
    at Un.e [as trigger] (smk.js:1274)
    at o.$$emit (smk.js:1299)
    at Proxy.e (smk.js:1274)
Qe @ smk.js:1274
smk.js:1274 [Vue warn]: Error in event handler for "directions-route.print": "TypeError: Cannot read property 'class' of undefined"

(found in <Root>)
ce @ smk.js:1274
Qe @ smk.js:1274
Xe @ smk.js:1274
Ze @ smk.js:1274
Mn.$emit @ smk.js:1274
e.emit @ smk.js:332
trigger @ smk.js:324
e @ smk.js:1274
$$emit @ smk.js:1299
e @ smk.js:1274
click @ VM353:3
i @ smk.js:1274
Mn.$emit @ smk.js:1274
clickButton @ smk.js:1299
e @ smk.js:1274
click @ VM281:6
i @ smk.js:1274
t._withTask.o._withTask @ smk.js:1274
smk.js:1274 TypeError: Cannot read property 'class' of undefined
    at smk.js:332
    at Array.forEach (<anonymous>)
    at e.getConfig (smk.js:332)
    at Un.print (smk.js:480)
    at Un.Mn.$emit (smk.js:1274)
    at e.emit (smk.js:332)
    at Un.trigger (smk.js:324)
    at Un.e [as trigger] (smk.js:1274)
    at o.$$emit (smk.js:1299)
    at Proxy.e (smk.js:1274)
Qe @ smk.js:1274
Xe @ smk.js:1274
Ze @ smk.js:1274
Mn.$emit @ smk.js:1274
e.emit @ smk.js:332
trigger @ smk.js:324
e @ smk.js:1274
$$emit @ smk.js:1299
e @ smk.js:1274
click @ VM353:3
i @ smk.js:1274
Mn.$emit @ smk.js:1274
clickButton @ smk.js:1299
e @ smk.js:1274
click @ VM281:6
i @ smk.js:1274
t._withTask.o._withTask @ smk.js:1274

**Comment by gk-tl** [comment]
@4:12 pm on March 18 - Print feature is working, but is very slow. I will try again later.

**Comment by gk-tl** [comment]
@4:37 pm on March 18 - tried again. It took approx. 10 seconds for the print preview screen to appear, 55 seconds for the file to load in the print preview, and 1 minute 42 seconds to print to PDF.  Total time nearly 3 minutes. Seems a bit long. Could also be my laptop. Could someone else try to confirm this is not an issue on my end.

**Comment by NicoledeGreef** [comment]
my experience is consistent with that of @gk-tl .  it eventually completed but the build is quite slow.  my laptop also starts humming pretty loudly while the preview is building.

**Comment by NicoledeGreef** [comment]
and...i just noticed that if i switch printers to "Save to PDF" instead of my default printer, it does the whole sequence over again.

**Comment by qqnluaq** [comment]
interesting. this seems to be a chrome thing. works fine in safari.

**Comment by NicoledeGreef** [comment]
Chrome definitely has some Print Preview issues judging from the Google search results.e.g. https://support.google.com/chrome/thread/4092279?hl=en

There are some feature flags you can modify in Chrome.
chrome://flags/

Previews Allowed - document did render; will test some more with it disabled

**Comment by qqnluaq** [comment]
made a few changes that seem to have improved the time to render the print preview

**Comment by NicoledeGreef** [comment]
i see that!  way faster from my vantage point.  nice.

**Comment by gk-tl** [comment]
Hi Nicole, Ben - tried it just now...still very slow on my end.

Time to load preview - 12 seconds
Time to generate preview - 2 minutes 8 seconds
Time to create PDF - 3 minutes 26 seconds

![image](https://user-images.githubusercontent.com/59627982/78186753-219f0080-7422-11ea-96d7-13415849d261.png)

**Comment by qqnluaq** [comment]
try it at https://translink-d.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Indeed. Much better. Thank you.
