### ISSUE TITLE
Reports & Notices - Capitalization of "Un-named" segments

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#98]
Is it possible to capitalize un-named portions of a route - highway ramp vs Highway Ramp? 

![image](https://user-images.githubusercontent.com/59627982/76987224-10250700-6900-11ea-9651-fc387b0ab97d.png)

**Comment by qqnluaq** [comment]
that data comes directly out of route planner, so this is an issue for @mraross

**Comment by gk-tl** [comment]
Thanks Ben.

@mraross I should also point out this is a very minor issue/low priority.

**Comment by NicoledeGreef** [comment]
I think this data is coming from the Route Planner.  @mraross  - can this be fixed at the source?

**Comment by mraross** [comment]
Yes and the source is ITN.

**Comment by NicoledeGreef** [comment]
Will you communicate that to the parties managing ITN?

**Comment by mraross** [comment]
Done by Ode to Joy.
